import {useEffect,useMemo,useRef,useState} from "react";
import {useLocation} from "react-router-dom";
import {Client} from "@stomp/stompjs";
import {getConversations,getMessages,sendMessage,startDirectChat,createGroupChat,searchChatUsers,getChatMembers,addChatMember,removeChatMember,leaveChatGroup,markChatRead,searchChatMessages,deleteChatMessage} from "../../api/interactionApi";
import {getPostPreview} from "../../api/postApi";
import {uploadFile} from "../../api/uploadApi";
import {useAuth} from "../../context/AuthContext";
import {MessageCircle,Send,RefreshCw,Paperclip,Users,Plus,UserPlus,LogOut,UserMinus,Search,X,FileText,Reply,Trash2,Forward,MoreVertical,CheckCheck,Clock3} from "lucide-react";

const idOf=x=>x?.id||x?._id;
const apiBase=import.meta.env.VITE_API_URL||"http://localhost:8080/api";
const wsBase=apiBase.replace(/^http:/,"ws:").replace(/^https:/,"wss:").replace(/\/api\/?$/,"/ws");
const timeOf=v=>v?new Date(v).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):"";

function Avatar({user,size="md",group=false}){return <div className={`chat-avatar chat-avatar-${size}`}>{user?.profileImage?<img src={user.profileImage} alt=""/>:group?<Users size={size==="sm"?15:18}/>:<span>{String(user?.name||user?.email||"?").slice(0,1).toUpperCase()}</span>}</div>}

export default function Messages(){
 const location=useLocation(); const {user}=useAuth(); const currentId=idOf(user);
 const [conversations,setConversations]=useState([]),[active,setActive]=useState(null),[meta,setMeta]=useState(null),[msgs,setMsgs]=useState([]),[members,setMembers]=useState([]);
 const [text,setText]=useState(""),[file,setFile]=useState(null),[reply,setReply]=useState(null),[typing,setTyping]=useState(false),[search,setSearch]=useState(""),[chatSearch,setChatSearch]=useState("");
 const [results,setResults]=useState([]),[loading,setLoading]=useState(true),[sending,setSending]=useState(false),[error,setError]=useState(""),[showNew,setShowNew]=useState(false),[showGroup,setShowGroup]=useState(false),[showMembers,setShowMembers]=useState(false),[addingMember,setAddingMember]=useState(false),[groupName,setGroupName]=useState(""),[selected,setSelected]=useState([]),[forwarding,setForwarding]=useState(null),[forwardTarget,setForwardTarget]=useState("");
 const bottom=useRef(null), stomp=useRef(null), typingTimer=useRef(null);
 const load=async()=>{setLoading(true);try{const r=await getConversations();const list=r.data?.data||[];const enriched=await Promise.all(list.map(async c=>{try{const p=c.postId?await getPostPreview(c.postId):null;return {...c,post:p?.data?.data||p?.data}}catch{return c}}));setConversations(enriched);const requested=location.state?.conversationId;if(requested&&enriched.some(x=>idOf(x)===requested))setActive(requested);else if(!active&&enriched[0])setActive(idOf(enriched[0]));}catch(e){setError(e.response?.data?.message||"Unable to load conversations.")}finally{setLoading(false)}};
 useEffect(()=>{load()},[]);
 useEffect(()=>{if(!active){setMsgs([]);setMeta(null);setMembers([]);return}let alive=true;const refresh=async()=>{try{const [mr,cr]=await Promise.all([getMessages(active),getConversations()]);if(alive){setMsgs(mr.data?.data||[]);const fresh=cr.data?.data||[];const c=fresh.find(x=>idOf(x)===active);if(c)setMeta(c);setConversations(old=>fresh.map(c2=>({...old.find(o=>idOf(o)===idOf(c2)),...c2})));await markChatRead(active).catch(()=>{});}}catch(e){if(alive)setError(e.response?.data?.message||"Unable to load messages.")}};refresh();const timer=setInterval(refresh,15000);return()=>{alive=false;clearInterval(timer)}},[active]);
 useEffect(()=>{if(!active)return;getChatMembers(active).then(r=>setMembers(r.data?.data||[])).catch(()=>setMembers([]))},[active,showMembers]);
 useEffect(()=>{bottom.current?.scrollIntoView({behavior:"smooth"})},[msgs]);
 useEffect(()=>{if(!active)return;const client=new Client({brokerURL:wsBase,connectHeaders:{Authorization:`Bearer ${localStorage.getItem("asmj_token")||""}`},reconnectDelay:5000,debug:()=>{}});client.onConnect=()=>{client.subscribe(`/topic/chat/${active}`,frame=>{try{const incoming=JSON.parse(frame.body);if(incoming.senderId===currentId)return;setMsgs(v=>v.some(m=>idOf(m)===idOf(incoming))?v:[...v,incoming]);markChatRead(active).catch(()=>{});setConversations(v=>v.map(c=>idOf(c)===active?{...c,lastMessage:incoming.message||"📎 Attachment",updatedAt:incoming.createdAt,unreadCount:0}:c));}catch{}});client.subscribe(`/topic/chat/${active}/typing`,frame=>{try{const t=JSON.parse(frame.body);if(t.userId!==currentId){setTyping(!!t.typing);clearTimeout(typingTimer.current);if(t.typing)typingTimer.current=setTimeout(()=>setTyping(false),2500);}}catch{}})};client.activate();stomp.current=client;return()=>{client.deactivate();stomp.current=null}},[active,currentId]);
 const directOther=useMemo(()=>members.find(m=>idOf(m)!==currentId),[members,currentId]);
 const title=meta?.conversationType==="GROUP"?(meta.name||"Group chat"):(directOther?.name||meta?.post?.title||"Direct chat");
 const subtitle=meta?.conversationType==="GROUP"?`${meta?.participants?.length||0} members`:(directOther?.email||meta?.post?.type||"Individual chat");
 const visibleMsgs=useMemo(()=>{const q=chatSearch.trim().toLowerCase();return q?msgs.filter(m=>String(m.message||"").toLowerCase().includes(q)):msgs},[msgs,chatSearch]);
 const doSearch=async()=>{try{const r=await searchChatUsers(search);setResults(r.data?.data||[])}catch{setResults([])}};
 const openDirect=async u=>{if(addingMember)return manageAdd(u);try{const r=await startDirectChat(idOf(u));const c=r.data?.data||r.data;setConversations(v=>[c,...v.filter(x=>idOf(x)!==idOf(c))]);setActive(idOf(c));closeModals()}catch(e){setError(e.response?.data?.message||"Could not start chat.")}};
 const createGroup=async()=>{if(!groupName.trim()||!selected.length){setError("Enter a group name and select at least one member.");return}try{const r=await createGroupChat({name:groupName.trim(),participantIds:selected.map(idOf)});const c=r.data?.data||r.data;setConversations(v=>[c,...v]);setActive(idOf(c));setGroupName("");setSelected([]);setShowGroup(false)}catch(e){setError(e.response?.data?.message||"Could not create group.")}};
 const closeModals=()=>{setShowNew(false);setShowGroup(false);setAddingMember(false);setSearch("");setResults([])};
 const attach=async()=>{if(!file)return[];if(file.size>10*1024*1024)throw new Error("Attachment must be 10 MB or smaller.");const allowed=["image/","application/pdf","text/","application/zip","application/msword","application/vnd.openxmlformats-officedocument"];if(!allowed.some(x=>file.type.startsWith(x)))throw new Error("This file type is not supported.");const r=await uploadFile(file,"chat");const a=r.data?.data||r.data;return [{publicId:a.publicId,secureUrl:a.secureUrl,fileName:a.fileName||file.name,mediaType:a.mediaType||file.type,resourceType:a.resourceType}]};
 const publishTyping=on=>{if(!stomp.current?.connected||!active)return;stomp.current.publish({destination:`/app/chat/${active}/typing`,body:JSON.stringify({userId:currentId,userName:user?.name||user?.email,typing:on})})};
 const onTextChange=e=>{setText(e.target.value);publishTyping(true);clearTimeout(typingTimer.current);typingTimer.current=setTimeout(()=>publishTyping(false),1000)};
 const send=async e=>{e.preventDefault();if((!text.trim()&&!file)||!active||sending)return;setSending(true);try{const attachments=await attach();const r=await sendMessage(active,{message:text.trim(),messageType:attachments.length?"ATTACHMENT":"TEXT",attachments,replyToMessageId:reply?.id||null,forwardedFromMessageId:null});const m=r.data?.data||r.data;setMsgs(v=>v.some(x=>idOf(x)===idOf(m))?v:[...v,m]);setText("");setFile(null);setReply(null);publishTyping(false);setConversations(v=>v.map(c=>idOf(c)===active?{...c,lastMessage:m.message||"📎 Attachment",updatedAt:m.createdAt}:c));}catch(e){setError(e.response?.data?.message||"Message could not be sent.")}finally{setSending(false)}};
 const manageAdd=async u=>{try{await addChatMember(active,idOf(u));setMembers((await getChatMembers(active)).data?.data||[]);closeModals();}catch(e){setError(e.response?.data?.message||"Could not add member.")}};
 const remove=async uid=>{try{await removeChatMember(active,uid);setMembers(v=>v.filter(x=>idOf(x)!==uid));}catch(e){setError(e.response?.data?.message||"Could not remove member.")}};
 const leave=async()=>{try{await leaveChatGroup(active);setConversations(v=>v.filter(c=>idOf(c)!==active));setActive(null);setShowMembers(false)}catch(e){setError(e.response?.data?.message||"Could not leave group.")}};
 const removeMessage=async m=>{if(!window.confirm("Delete this message?"))return;try{await deleteChatMessage(active,idOf(m));setMsgs(v=>v.filter(x=>idOf(x)!==idOf(m)))}catch(e){setError(e.response?.data?.message||"Could not delete message.")}};
 const doForward=async()=>{if(!forwardTarget||!forwarding)return;try{await sendMessage(forwardTarget,{message:forwarding.message||"",messageType:forwarding.messageType||"TEXT",attachments:forwarding.attachments||[],replyToMessageId:null,forwardedFromMessageId:idOf(forwarding)});setForwarding(null);setForwardTarget("")}catch(e){setError(e.response?.data?.message||"Could not forward message.")}};
 const searchServer=async()=>{if(!chatSearch.trim()){const r=await getMessages(active);setMsgs(r.data?.data||[]);return}try{const r=await searchChatMessages(active,chatSearch);setMsgs(r.data?.data||[])}catch(e){setError(e.response?.data?.message||"Search failed.")}};
 return <div className="page-shell chat-bg"><div className="mb-5 flex flex-col gap-3 sm:flex-row sm:items-end sm:justify-between"><div><p className="eyebrow">MESSAGES</p><h1 className="page-title">Chat & Messaging</h1><p className="mt-2 text-sm text-slate-500">Private chat, groups, attachments, replies, forwarding, unread counts and live WebSocket updates.</p></div><div className="flex flex-wrap gap-2"><button className="btn-secondary" onClick={()=>{setShowNew(true);setAddingMember(false)}}><Plus size={16}/> New chat</button><button className="btn-primary" onClick={()=>setShowGroup(true)}><Users size={16}/> New group</button><button className="btn-secondary" onClick={load}><RefreshCw size={16}/> Refresh</button></div></div>
 {error&&<div className="mb-5 flex items-center justify-between rounded-2xl border border-red-100 bg-red-50 px-4 py-3 text-sm font-semibold text-red-700"><span>{error}</span><button onClick={()=>setError("")}><X size={16}/></button></div>}
 <div className="chat-shell chat-shell-v18"><aside className="chat-list"><div className="chat-list-head"><b>Chats</b><span>{conversations.length}</span></div><div className="chat-search"><Search size={15}/><input value={chatSearch} onChange={e=>setChatSearch(e.target.value)} placeholder="Search messages / chats"/><button onClick={searchServer}><Search size={14}/></button></div>{loading?<div className="p-6 text-sm text-slate-400">Loading conversations…</div>:conversations.map(c=>{const selectedChat=idOf(c)===active;const label=c.conversationType==="GROUP"?(c.name||"Group chat"):c.postId?(c.post?.title||"Listing chat"):"Direct chat";return <button key={idOf(c)} onClick={()=>{setActive(idOf(c));setChatSearch("")}} className={`chat-item chat-item-v18 ${selectedChat?"chat-item-active":""}`}><Avatar group={c.conversationType==="GROUP"} user={c.post?.images?.[0]?{profileImage:c.post.images[0]}:null}/><div className="min-w-0 flex-1 text-left"><div className="flex items-center gap-2"><b className="block truncate">{label}</b>{c.unreadCount>0&&<span className="unread-badge">{c.unreadCount>99?"99+":c.unreadCount}</span>}</div><span className="block truncate text-xs text-slate-400">{c.conversationType==="GROUP"?`${c.participants?.length||0} members`:(c.post?.type||"Individual")}</span><span className="mt-1 block truncate text-xs text-slate-500">{c.lastMessage||"Start the conversation"}</span></div><time className="self-start text-[10px] text-slate-400">{c.updatedAt?timeOf(c.updatedAt):""}</time></button>})}{!loading&&!conversations.length&&<div className="p-8 text-center text-sm text-slate-400"><MessageCircle className="mx-auto mb-2"/>No conversations yet.</div>}</aside>
 <section className="chat-window">{active?<><header className="chat-header chat-header-v18"><div className="flex min-w-0 flex-1 items-center gap-3"><Avatar group={meta?.conversationType==="GROUP"} user={directOther}/><div className="min-w-0"><h2 className="truncate font-black">{title}</h2><p className="text-xs text-slate-400">{typing?<span className="font-semibold text-emerald-600">typing…</span>:subtitle}</p></div></div><div className="flex gap-2">{meta?.conversationType==="GROUP"&&<button className="btn-secondary" onClick={()=>setShowMembers(v=>!v)}><Users size={16}/> Members</button>}</div></header>
 {showMembers&&meta?.conversationType==="GROUP"&&<div className="chat-members-panel"><div className="flex items-center justify-between"><div><p className="eyebrow">GROUP</p><h3 className="font-black">{meta.name}</h3></div><button className="icon-btn" onClick={()=>setShowMembers(false)}><X size={16}/></button></div><div className="mt-3 space-y-2">{members.map(m=><div key={idOf(m)} className="chat-member"><Avatar user={m} size="sm"/><div className="min-w-0 flex-1"><b className="block truncate text-sm">{m.name||m.email}</b><span className="text-xs text-slate-400">{m.email}</span></div>{idOf(m)===meta.createdBy&&<span className="owner-badge">Owner</span>}{meta.createdBy===currentId&&idOf(m)!==currentId&&<button className="icon-btn !h-8 !w-8" onClick={()=>remove(idOf(m))}><UserMinus size={14}/></button>}</div>)}</div><div className="mt-4 flex gap-2"><button className="btn-secondary" onClick={()=>{setShowNew(true);setAddingMember(true)}}><UserPlus size={16}/> Add member</button><button className="btn-secondary text-red-600" onClick={leave}><LogOut size={16}/> Exit group</button></div></div>}
 <div className="chat-messages chat-messages-v18">{visibleMsgs.map(m=>{const mine=m.senderId===currentId;return <div key={idOf(m)} className={`message-row ${mine?"message-row-mine":""}`}><div className={`message-bubble ${mine?"message-mine":"message-theirs"}`}>{!mine&&meta?.conversationType==="GROUP"&&<div className="mb-1 text-[11px] font-black text-slate-500">{m.senderName||m.senderId}</div>}{m.replyPreview&&<div className={`reply-preview ${mine?"reply-preview-mine":""}`}><Reply size={12}/><span className="truncate">{m.replyPreview}</span></div>}{m.forwardedFromMessageId&&<div className="mb-1 text-[10px] font-bold opacity-70">↗ Forwarded</div>}{m.attachments?.map(a=><a key={a.publicId||a.secureUrl} href={a.secureUrl} target="_blank" rel="noreferrer" className={`attachment-card ${mine?"attachment-mine":""}`}><FileText size={16}/><span className="min-w-0 flex-1 truncate">{a.fileName||"Attachment"}</span><span className="text-[10px]">Open</span></a>)}{m.message&&<p>{m.message}</p>}<div className="message-meta"><span>{timeOf(m.createdAt)}</span>{mine&&(m.read?<CheckCheck size={14} className="text-sky-300"/>:<CheckCheck size={14} className="opacity-50"/>)}</div><div className="message-actions"><button title="Reply" onClick={()=>setReply(m)}><Reply size={13}/></button><button title="Forward" onClick={()=>{setForwarding(m);setForwardTarget("")}}><Forward size={13}/></button>{mine&&<button title="Delete" onClick={()=>removeMessage(m)}><Trash2 size={13}/></button>}</div></div></div>})}{!visibleMsgs.length&&<div className="grid h-full min-h-[28rem] place-items-center text-center text-sm text-slate-400"><div><MessageCircle className="mx-auto mb-2" size={34}/>{chatSearch?<p>No matching messages.</p>:<p>No messages yet. Say hello.</p>}</div></div>}<div ref={bottom}/></div>
 {reply&&<div className="reply-compose"><Reply size={15}/><div className="min-w-0 flex-1"><b className="text-xs">Replying to {reply.senderName||"message"}</b><p className="truncate text-xs text-slate-500">{reply.message||"Attachment"}</p></div><button onClick={()=>setReply(null)}><X size={15}/></button></div>}
 <form onSubmit={send} className="chat-compose chat-compose-v18"><div className="flex min-w-0 flex-1 items-center gap-2">{file&&<div className="file-chip"><Paperclip size={13}/><span>{file.name}</span><button type="button" onClick={()=>setFile(null)}><X size={13}/></button></div>}<label className="icon-btn cursor-pointer" title="Attach file"><Paperclip size={18}/><input type="file" accept="image/*,.pdf,.txt,.doc,.docx,.zip" className="hidden" onChange={e=>{const next=e.target.files?.[0]||null;if(next&&next.size>10*1024*1024){setError("Attachment must be 10 MB or smaller.");return}setFile(next);setError("")}}/></label><input className="input chat-input" value={text} onChange={onTextChange} placeholder="Type a message…" disabled={sending}/></div><button className="btn-primary !rounded-full !px-5" disabled={sending||(!text.trim()&&!file)}><Send size={16}/>{sending?"Sending":"Send"}</button></form>
 </>:<div className="grid h-full min-h-[38rem] place-items-center text-center text-slate-400"><div><MessageCircle className="mx-auto" size={42}/><p className="mt-3 font-semibold">Select a chat or start a new conversation.</p></div></div>}</section></div>
 {showNew&&<Modal title={addingMember?"Add group member":"New individual chat"} onClose={closeModals}><div className="flex gap-2"><input className="input" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&doSearch()} placeholder="Search by name or email"/><button className="btn-primary" onClick={doSearch}><Search size={16}/></button></div><div className="mt-4 max-h-80 space-y-2 overflow-auto">{results.map(u=><button key={idOf(u)} onClick={()=>openDirect(u)} className="flex w-full items-center gap-3 rounded-2xl p-3 text-left hover:bg-slate-50"><Avatar user={u}/><div className="min-w-0"><b className="block truncate">{u.name||u.email}</b><span className="text-xs text-slate-400">{u.email}</span></div></button>)}</div></Modal>}
 {showGroup&&<Modal title="Create group" onClose={()=>setShowGroup(false)}><input className="input" value={groupName} onChange={e=>setGroupName(e.target.value)} placeholder="Group name"/><div className="mt-3 flex gap-2"><input className="input" value={search} onChange={e=>setSearch(e.target.value)} onKeyDown={e=>e.key==="Enter"&&doSearch()} placeholder="Find members"/><button className="btn-secondary" onClick={doSearch}><Search size={16}/></button></div><div className="mt-3 max-h-64 space-y-2 overflow-auto">{results.map(u=>{const picked=selected.some(x=>idOf(x)===idOf(u));return <button key={idOf(u)} onClick={()=>setSelected(v=>picked?v.filter(x=>idOf(x)!==idOf(u)):[...v,u])} className={`flex w-full items-center gap-3 rounded-xl p-3 text-left ${picked?"bg-slate-100":"hover:bg-slate-50"}`}><Avatar user={u} size="sm"/><div className="flex-1"><b className="block text-sm">{u.name||u.email}</b><span className="text-xs text-slate-400">{u.email}</span></div>{picked&&<span className="text-xs font-black">Selected</span>}</button>})}</div><button className="btn-primary mt-4 w-full" onClick={createGroup}><Users size={16}/> Create group ({selected.length})</button></Modal>}
 {forwarding&&<Modal title="Forward message" onClose={()=>setForwarding(null)}><p className="rounded-xl bg-slate-50 p-3 text-sm text-slate-600">{forwarding.message||"📎 Attachment"}</p><label className="label mt-4">Choose conversation</label><select className="input" value={forwardTarget} onChange={e=>setForwardTarget(e.target.value)}><option value="">Select chat</option>{conversations.filter(c=>idOf(c)!==active).map(c=><option key={idOf(c)} value={idOf(c)}>{c.name||c.post?.title||"Direct chat"}</option>)}</select><button className="btn-primary mt-4 w-full" disabled={!forwardTarget} onClick={doForward}><Forward size={16}/> Forward</button></Modal>}
 </div>
}
function Modal({title,onClose,children}){return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/45 p-4"><div className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex items-center justify-between"><div><p className="eyebrow">CHAT</p><h2 className="text-2xl font-black">{title}</h2></div><button className="icon-btn" onClick={onClose}><X size={16}/></button></div><div className="mt-5">{children}</div></div></div>}
