package com.asmj.marketplace.event.service;
import com.asmj.marketplace.event.model.*;import com.asmj.marketplace.event.repository.*;import com.asmj.marketplace.event.controller.EventDtos.*;import com.asmj.marketplace.user.model.User;import com.asmj.marketplace.user.repository.UserRepository;import com.asmj.marketplace.vendor.model.Vendor;import com.asmj.marketplace.vendor.repository.VendorRepository;import com.asmj.marketplace.notification.service.NotificationService;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import java.time.*;import java.util.*;
@Service @RequiredArgsConstructor public class EventMarketplaceService { final EventListingRepository events; final EventRegistrationRepository registrations; final UserRepository users; final VendorRepository vendors; final NotificationService notifications;
 public List<EventListing> publicEvents(){return events.findByApprovedTrueAndActiveTrueAndStatusOrderByEventDateAscStartTimeAsc("PUBLISHED");}
 public List<EventListing> vendorEvents(String email){return events.findByVendorIdOrderByEventDateDescStartTimeDesc(vendor(email).getId());}
 public EventListing save(String email,EventRequest r,String id){Vendor v=vendor(email); if(r.name()==null||r.name().isBlank())throw new IllegalArgumentException("Event name is required"); if(r.eventDate()==null||r.startTime()==null||r.endTime()==null||!r.startTime().isBefore(r.endTime()))throw new IllegalArgumentException("Valid event date and time are required"); if(r.eventDate().isBefore(LocalDate.now()))throw new IllegalArgumentException("Event date cannot be in the past"); if(r.capacity()<=0)throw new IllegalArgumentException("Capacity must be greater than zero"); EventListing e=id==null?EventListing.builder().vendorId(v.getId()).status("PENDING_APPROVAL").approved(false).active(false).views(0).createdAt(Instant.now()).build():events.findById(id).orElseThrow(); if(!Objects.equals(e.getVendorId(),v.getId()))throw new IllegalArgumentException("Not your event"); e.setName(r.name().trim());e.setCategory(r.category());e.setDescription(r.description());e.setEventDate(r.eventDate());e.setStartTime(r.startTime());e.setEndTime(r.endTime());e.setVenue(req(r.venue(),"Venue is required"));e.setAddress(req(r.address(),"Address is required"));e.setCity(req(r.city(),"City is required"));e.setCapacity(r.capacity()); if(id==null)e.setAvailableSeats(r.capacity());else e.setAvailableSeats(Math.min(e.getAvailableSeats(),r.capacity()));e.setTicketPrice(Math.max(0,r.ticketPrice()));e.setRegistrationDeadline(r.registrationDeadline());e.setImages(r.images()==null?new ArrayList<>():r.images());e.setTerms(r.terms());e.setOrganizerName(v.getBusinessName());e.setUpdatedAt(Instant.now());return events.save(e);}
 public EventRegistration register(String email,String eventId,RegistrationRequest r){User u=user(email);EventListing e=events.findById(eventId).orElseThrow();if(!e.isApproved()||!e.isActive()||!"PUBLISHED".equals(e.getStatus()))throw new IllegalArgumentException("Event unavailable");int q=Math.max(1,r.quantity());if(q>e.getAvailableSeats())throw new IllegalArgumentException("Only "+e.getAvailableSeats()+" seats are available");if(e.getRegistrationDeadline()!=null&&LocalDateTime.now().isAfter(e.getRegistrationDeadline()))throw new IllegalArgumentException("Registration deadline has passed");double total=e.getTicketPrice()*q;Instant now=Instant.now();EventRegistration x=EventRegistration.builder().registrationNumber("ASMJ-E"+String.format("%08d",Math.abs(UUID.randomUUID().hashCode()))).eventId(e.getId()).vendorId(e.getVendorId()).userId(u.getId()).attendeeName(req(r.attendeeName()==null?u.getName():r.attendeeName(),"Attendee name required")).attendeeMobile(r.attendeeMobile()==null?u.getMobile():r.attendeeMobile()).quantity(q).unitPrice(e.getTicketPrice()).totalAmount(total).status("CONFIRMED").registeredAt(now).history(new ArrayList<>()).build();x.getHistory().add(EventRegistration.StatusEntry.builder().status("CONFIRMED").actorId(u.getId()).note("Event registration confirmed").at(now).build());e.setAvailableSeats(e.getAvailableSeats()-q);events.save(e);EventRegistration saved=registrations.save(x);Vendor v=vendors.findById(e.getVendorId()).orElse(null);if(v!=null)notifications.create(v.getUserId(),"New event registration",saved.getRegistrationNumber()+" registered for "+e.getName(),"EVENT_REGISTRATION");return saved;}
 public List<EventRegistration> my(String email){return registrations.findByUserIdOrderByRegisteredAtDesc(user(email).getId());} public List<EventRegistration> vendorRegistrations(String email){return registrations.findByVendorIdOrderByRegisteredAtDesc(vendor(email).getId());}
 public EventRegistration cancel(String email,String id){EventRegistration x=registrations.findById(id).orElseThrow();User u=user(email);if(!Objects.equals(x.getUserId(),u.getId())&&!u.getRoles().contains(User.Role.ADMIN))throw new IllegalArgumentException("Not authorized");if(!"CONFIRMED".equals(x.getStatus()))throw new IllegalArgumentException("Registration cannot be cancelled");EventListing e=events.findById(x.getEventId()).orElseThrow();x.setStatus("CANCELLED");x.setCancelledAt(Instant.now());x.getHistory().add(EventRegistration.StatusEntry.builder().status("CANCELLED").actorId(u.getId()).note("Registration cancelled").at(Instant.now()).build());e.setAvailableSeats(Math.min(e.getCapacity(),e.getAvailableSeats()+x.getQuantity()));events.save(e);return registrations.save(x);}
 public EventListing approve(String id,boolean ok,String note){EventListing e=events.findById(id).orElseThrow();e.setApproved(ok);e.setActive(ok);e.setStatus(ok?"PUBLISHED":"REJECTED");e.setUpdatedAt(Instant.now());if(ok){Vendor v=vendors.findById(e.getVendorId()).orElse(null);if(v!=null)notifications.create(v.getUserId(),"Event approved",e.getName()+" is now published.","EVENT_APPROVAL");}return events.save(e);}
 public List<EventListing> adminEvents(){return events.findAll();}
 User user(String e){return users.findByEmailIgnoreCase(e).orElseThrow();}Vendor vendor(String e){return vendors.findByUserId(user(e).getId()).orElseThrow(()->new IllegalArgumentException("Vendor profile not found"));}String req(String s,String m){if(s==null||s.isBlank())throw new IllegalArgumentException(m);return s.trim();}
}
