package com.asmj.marketplace.insurance.service;
import com.asmj.marketplace.insurance.model.*;import com.asmj.marketplace.insurance.repository.*;import com.asmj.marketplace.insurance.controller.InsuranceDtos.*;import com.asmj.marketplace.user.model.User;import com.asmj.marketplace.user.repository.UserRepository;import com.asmj.marketplace.vendor.model.Vendor;import com.asmj.marketplace.vendor.repository.VendorRepository;import com.asmj.marketplace.notification.service.NotificationService;import lombok.RequiredArgsConstructor;import org.springframework.stereotype.Service;import java.time.*;import java.util.*;
@Service @RequiredArgsConstructor public class InsuranceMarketplaceService { final InsurancePlanRepository plans; final InsuranceQuoteRequestRepository quotes; final UserRepository users; final VendorRepository vendors; final NotificationService notifications;
 public List<InsurancePlan> publicPlans(){return plans.findByApprovedTrueAndActiveTrueOrderByFeaturedDescCreatedAtDesc();}
 public InsurancePlan get(String id){InsurancePlan p=plans.findById(id).orElseThrow();p.setViews(p.getViews()+1);return plans.save(p);}
 public List<InsurancePlan> vendorPlans(String email){return plans.findByVendorIdOrderByCreatedAtDesc(vendor(email).getId());}
 public InsurancePlan save(String email,PlanRequest r,String id){Vendor v=vendor(email); if(blank(r.insurerName())||blank(r.planName())||blank(r.insuranceType()))throw new IllegalArgumentException("Insurer, plan name and insurance type are required");if(r.premium()<0||r.sumInsured()<0)throw new IllegalArgumentException("Premium and sum insured cannot be negative");InsurancePlan p=id==null?InsurancePlan.builder().vendorId(v.getId()).approved(false).active(false).views(0).createdAt(Instant.now()).build():plans.findById(id).orElseThrow();if(!Objects.equals(p.getVendorId(),v.getId()))throw new IllegalArgumentException("Not your insurance plan");p.setInsurerName(r.insurerName().trim());p.setPlanName(r.planName().trim());p.setInsuranceType(r.insuranceType());p.setDescription(r.description());p.setCoverageSummary(r.coverageSummary());p.setSumInsured(r.sumInsured());p.setPremium(r.premium());p.setPremiumFrequency(r.premiumFrequency());p.setMinEntryAge(r.minEntryAge());p.setMaxEntryAge(r.maxEntryAge());p.setCity(r.city());p.setBenefits(r.benefits()==null?new ArrayList<>():r.benefits());p.setExclusions(r.exclusions()==null?new ArrayList<>():r.exclusions());p.setClaimProcess(r.claimProcess());p.setClaimSettlementInfo(r.claimSettlementInfo());p.setDocuments(r.documents()==null?new ArrayList<>():r.documents());p.setImages(r.images()==null?new ArrayList<>():r.images());p.setFeatured(r.featured());p.setUpdatedAt(Instant.now());return plans.save(p);}
 public InsuranceQuoteRequest requestQuote(String email,String id,QuoteRequest r){User u=user(email);InsurancePlan p=plans.findById(id).orElseThrow();if(!p.isApproved()||!p.isActive())throw new IllegalArgumentException("Insurance plan unavailable");if(r.age()!=null&&((p.getMinEntryAge()!=null&&r.age()<p.getMinEntryAge())||(p.getMaxEntryAge()!=null&&r.age()>p.getMaxEntryAge())))throw new IllegalArgumentException("Age is outside this plan's entry range");int members=Math.max(1,r.members()==null?1:r.members());double estimate=p.getPremium()*members;Instant now=Instant.now();String num="ASMJ-IQ"+String.format("%08d",Math.abs(UUID.randomUUID().hashCode()));InsuranceQuoteRequest q=InsuranceQuoteRequest.builder().quoteNumber(num).planId(id).vendorId(p.getVendorId()).userId(u.getId()).customerName(u.getName()).customerMobile(u.getMobile()).customerEmail(u.getEmail()).age(r.age()).members(members).city(r.city()).occupation(r.occupation()).coverageNeed(r.coverageNeed()).estimatedPremium(estimate).status("REQUESTED").history(new ArrayList<>()).createdAt(now).updatedAt(now).build();q.getHistory().add(InsuranceQuoteRequest.StatusEntry.builder().status("REQUESTED").actorId(u.getId()).note("Quote request submitted").at(now).build());InsuranceQuoteRequest saved=quotes.save(q);Vendor v=vendors.findById(p.getVendorId()).orElse(null);if(v!=null)notifications.create(v.getUserId(),"New insurance quote request",num+" requested for "+p.getPlanName(),"INSURANCE_QUOTE");return saved;}
 public List<InsuranceQuoteRequest> myQuotes(String email){return quotes.findByUserIdOrderByCreatedAtDesc(user(email).getId());} public List<InsuranceQuoteRequest> vendorQuotes(String email){return quotes.findByVendorIdOrderByCreatedAtDesc(vendor(email).getId());}
 public InsuranceQuoteRequest updateQuote(String email,String id,StatusRequest r){Vendor v=vendor(email);InsuranceQuoteRequest q=quotes.findById(id).orElseThrow();if(!Objects.equals(q.getVendorId(),v.getId()))throw new IllegalArgumentException("Not authorized");Set<String> allowed=Set.of("CONTACTED","QUOTE_SHARED","CLOSED","REJECTED");if(!allowed.contains(r.status()))throw new IllegalArgumentException("Invalid quote status");Instant now=Instant.now();q.setStatus(r.status());q.setVendorNotes(r.note());q.setUpdatedAt(now);if(q.getHistory()==null)q.setHistory(new ArrayList<>());q.getHistory().add(InsuranceQuoteRequest.StatusEntry.builder().status(r.status()).actorId(v.getUserId()).note(r.note()).at(now).build());InsuranceQuoteRequest saved=quotes.save(q);notifications.create(q.getUserId(),"Insurance quote updated",q.getQuoteNumber()+" is now "+r.status(),"INSURANCE_QUOTE_UPDATE");return saved;}
 public List<InsurancePlan> adminPlans(){return plans.findAll();} public InsurancePlan approve(String id,boolean ok){InsurancePlan p=plans.findById(id).orElseThrow();p.setApproved(ok);p.setActive(ok);p.setUpdatedAt(Instant.now());if(ok){Vendor v=vendors.findById(p.getVendorId()).orElse(null);if(v!=null)notifications.create(v.getUserId(),"Insurance plan approved",p.getPlanName()+" is now published","INSURANCE_APPROVAL");}return plans.save(p);}
 public List<InsuranceQuoteRequest> adminQuotes(){return quotes.findAll();}
 User user(String e){return users.findByEmailIgnoreCase(e).orElseThrow();}Vendor vendor(String e){return vendors.findByUserId(user(e).getId()).orElseThrow(()->new IllegalArgumentException("Vendor profile not found"));}boolean blank(String s){return s==null||s.isBlank();}
}
