package com.asmj.marketplace.product.service;
import com.asmj.marketplace.product.dto.ProductDtos;
import com.asmj.marketplace.product.dto.ProductDtos.*;import com.asmj.marketplace.product.model.*;import com.asmj.marketplace.product.repository.*;import com.asmj.marketplace.user.model.User;import com.asmj.marketplace.user.repository.UserRepository;import com.asmj.marketplace.vendor.model.Vendor;import com.asmj.marketplace.vendor.repository.VendorRepository;import com.asmj.marketplace.notification.service.NotificationService;import lombok.RequiredArgsConstructor;import org.springframework.data.mongodb.core.MongoTemplate;import org.springframework.data.mongodb.core.query.*;import org.springframework.data.mongodb.core.query.Update;import org.springframework.stereotype.Service;import java.time.*;import java.util.*;
@Service @RequiredArgsConstructor public class ProductService{
 final ProductRepository products;final CartRepository carts;final OrderRepository orders;final CouponRepository coupons;final UserRepository users;final VendorRepository vendors;final NotificationService notifications;final MongoTemplate mongo;
 public List<Product> publicProducts(){return products.findByActiveTrueAndApprovedTrueOrderByCreatedAtDesc();}
 public List<Product> vendorProducts(String email){Vendor v=vendor(email);return products.findByVendorIdOrderByCreatedAtDesc(v.getId());}
 public Product save(String email,ProductDtos.ProductRequest r,String id){Vendor v=vendor(email);if(id!=null&&!id.isBlank()){Product p=products.findById(id).orElseThrow();if(!Objects.equals(p.getVendorId(),v.getId()))throw new IllegalArgumentException("Not your product");return products.save(map(p,r));}if(products.findBySkuIgnoreCase(r.sku()).isPresent())throw new IllegalArgumentException("SKU already exists");Instant n=Instant.now();return products.save(map(Product.builder().vendorId(v.getId()).approved(false).active(false).createdAt(n).build(),r));}
 Product map(Product p,ProductDtos.ProductRequest r){p.setName(req(r.name(),"Product name is required"));p.setSku(req(r.sku(),"SKU is required").toUpperCase());p.setCategoryId(r.categoryId());p.setBrand(r.brand());p.setDescription(r.description());p.setUnit(r.unit());p.setPrice(Math.max(0,r.price()));p.setMrp(Math.max(p.getPrice(),r.mrp()));p.setTaxRate(Math.max(0,r.taxRate()));p.setImages(r.images()==null?new ArrayList<>():r.images());p.setFeatured(r.featured());if(r.variants()!=null){List<Product.Variant> vs=new ArrayList<>();for(Map<String,Object> m:r.variants()){vs.add(Product.Variant.builder().id(String.valueOf(m.getOrDefault("id",UUID.randomUUID()))).name(String.valueOf(m.getOrDefault("name","Default"))).sku(String.valueOf(m.getOrDefault("sku",p.getSku()))).price(num(m.get("price"),p.getPrice())).mrp(num(m.get("mrp"),p.getMrp())).stock((int)num(m.get("stock"),0)).lowStockThreshold((int)num(m.get("lowStockThreshold"),5)).active(!Boolean.FALSE.equals(m.get("active"))).attributes((Map<String,String>)m.getOrDefault("attributes",Map.of())).build());}p.setVariants(vs);}if((p.getVariants()==null||p.getVariants().isEmpty())){p.setVariants(new ArrayList<>(List.of(Product.Variant.builder().id(UUID.randomUUID().toString()).name("Default").sku(p.getSku()).price(p.getPrice()).mrp(p.getMrp()).stock(r.stock()==null?0:Math.max(0,r.stock())).lowStockThreshold(r.lowStockThreshold()==null?5:Math.max(0,r.lowStockThreshold())).active(true).attributes(Map.of()).build())));}p.setUpdatedAt(Instant.now());return p;}
 double num(Object x,double d){return x instanceof Number?n(((Number)x).doubleValue()):d;}double n(double x){return x;}
 public Cart add(String email,CartRequest r){User u=user(email);Product p=products.findById(r.productId()).orElseThrow();if(!p.isActive()||!p.isApproved())throw new IllegalArgumentException("Product unavailable");Product.Variant v=findVariant(p,r.variantId());if(r.quantity()<1)throw new IllegalArgumentException("Quantity must be positive");if(v!=null&&v.getStock()<r.quantity())throw new IllegalArgumentException("Insufficient stock");Cart c=carts.findByUserId(u.getId()).orElseGet(()->Cart.builder().userId(u.getId()).items(new ArrayList<>()).build());Cart.Item item=c.getItems().stream().filter(i->Objects.equals(i.getProductId(),p.getId())&&Objects.equals(i.getVariantId(),r.variantId())).findFirst().orElse(null);if(item==null)c.getItems().add(Cart.Item.builder().productId(p.getId()).variantId(r.variantId()).vendorId(p.getVendorId()).name(p.getName()).variantName(v==null?null:v.getName()).image(p.getImages()==null||p.getImages().isEmpty()?null:p.getImages().get(0)).quantity(r.quantity()).unitPrice(v==null?p.getPrice():v.getPrice()).build());else{item.setQuantity(item.getQuantity()+r.quantity());if(v!=null&&item.getQuantity()>v.getStock())throw new IllegalArgumentException("Insufficient stock");}c.setUpdatedAt(Instant.now());return carts.save(c);}
 public Cart cart(String email){User u=user(email);return carts.findByUserId(u.getId()).orElse(Cart.builder().userId(u.getId()).items(new ArrayList<>()).updatedAt(Instant.now()).build());}
 public Cart remove(String email,String productId,String variantId){User u=user(email);Cart c=cart(email);c.getItems().removeIf(i->Objects.equals(i.getProductId(),productId)&&Objects.equals(i.getVariantId(),variantId));return carts.save(c);}
 public List<Order> myOrders(String email){return orders.findByCustomerIdOrderByCreatedAtDesc(user(email).getId());}public List<Order> vendorOrders(String email){return orders.findByVendorIdOrderByCreatedAtDesc(vendor(email).getId());}
 public Order checkout(String email,CheckoutRequest req){User u=user(email);Cart c=cart(email);if(c.getItems().isEmpty())throw new IllegalArgumentException("Cart is empty");Order.Address a=address(req.address());if(a.getName()==null||a.getName().isBlank()||a.getMobile()==null||a.getMobile().isBlank()||a.getLine1()==null||a.getLine1().isBlank()||a.getCity()==null||a.getState()==null||a.getPincode()==null)throw new IllegalArgumentException("Complete shipping address is required");Map<String,List<Cart.Item>> groups=new LinkedHashMap<>();for(Cart.Item i:c.getItems())groups.computeIfAbsent(i.getVendorId(),k->new ArrayList<>()).add(i);if(groups.size()>1)throw new IllegalArgumentException("Cart contains products from multiple vendors. Checkout one vendor at a time in this release.");String vendorId=groups.keySet().iterator().next();double subtotal=0,tax=0;List<Order.Item> items=new ArrayList<>();for(Cart.Item ci:groups.values().iterator().next()){Product p=products.findById(ci.getProductId()).orElseThrow();Product.Variant v=findVariant(p,ci.getVariantId());reserveStock(p,v,ci.getQuantity());double line=ci.getUnitPrice()*ci.getQuantity();double lineTax=line*p.getTaxRate()/100;subtotal+=line;tax+=lineTax;items.add(Order.Item.builder().productId(p.getId()).variantId(ci.getVariantId()).name(p.getName()).variantName(ci.getVariantName()).quantity(ci.getQuantity()).unitPrice(ci.getUnitPrice()).taxAmount(lineTax).total(line+lineTax).build());}Coupon coupon=validCoupon(req.couponCode(),vendorId);double discount=discount(coupon,subtotal+tax);double shipping=0,total=Math.max(0,subtotal+tax+shipping-discount);Instant now=Instant.now();Order o=Order.builder().orderNumber("ASMJ-P"+String.format("%08d",Math.abs(UUID.randomUUID().hashCode()))).customerId(u.getId()).vendorId(vendorId).items(items).shippingAddress(a).subtotal(subtotal).tax(tax).discount(discount).shippingFee(shipping).total(total).couponCode(coupon==null?null:coupon.getCode()).paymentStatus("PENDING").status(Order.Status.PLACED).statusHistory(new ArrayList<>()).createdAt(now).updatedAt(now).build();o.getStatusHistory().add(Order.StatusEntry.builder().status(Order.Status.PLACED).actorId(u.getId()).note("Order placed").at(now).build());Order saved=orders.save(o);if(coupon!=null){coupon.setUsedCount(coupon.getUsedCount()+1);coupons.save(coupon);}c.getItems().clear();carts.save(c);Vendor v=vendors.findById(vendorId).orElse(null);if(v!=null)notifications.create(v.getUserId(),"New product order",saved.getOrderNumber()+" has been placed.","PRODUCT_ORDER");return saved;}
 void reserveStock(Product p,Product.Variant v,int qty){if(v==null)return;Query q=new Query(Criteria.where("_id").is(p.getId()).and("variants").elemMatch(Criteria.where("id").is(v.getId()).and("stock").gte(qty)));Update u=new Update().inc("variants.$.stock",-qty);if(mongo.updateFirst(q,u,Product.class).getModifiedCount()!=1)throw new IllegalArgumentException("Stock changed. Please review your cart and try again.");}
 public Order updateStatus(String email,String id,StatusRequest req){Order o=orders.findById(id).orElseThrow();User u=user(email);boolean ok=u.getRoles().contains(User.Role.ADMIN);if(!ok){Vendor v=vendors.findByUserId(u.getId()).orElseThrow();ok=Objects.equals(v.getId(),o.getVendorId());}if(!ok)throw new IllegalArgumentException("Not authorized");validateTransition(o.getStatus(),req.status());if(req.status()==Order.Status.CANCELLED) restoreStock(o);o.setStatus(req.status());o.getStatusHistory().add(Order.StatusEntry.builder().status(req.status()).actorId(u.getId()).note(req.note()).at(Instant.now()).build());o.setUpdatedAt(Instant.now());Order saved=orders.save(o);notifications.create(o.getCustomerId(),"Order update",o.getOrderNumber()+" is now "+req.status()+".","PRODUCT_ORDER");return saved;}
 void validateTransition(Order.Status from,Order.Status to){if(from==to)return;Map<Order.Status,Set<Order.Status>> m=Map.of(Order.Status.PLACED,Set.of(Order.Status.CONFIRMED,Order.Status.CANCELLED),Order.Status.CONFIRMED,Set.of(Order.Status.PROCESSING,Order.Status.CANCELLED),Order.Status.PROCESSING,Set.of(Order.Status.PACKED,Order.Status.CANCELLED),Order.Status.PACKED,Set.of(Order.Status.SHIPPED),Order.Status.SHIPPED,Set.of(Order.Status.OUT_FOR_DELIVERY),Order.Status.OUT_FOR_DELIVERY,Set.of(Order.Status.DELIVERED),Order.Status.DELIVERED,Set.of(Order.Status.RETURN_REQUESTED),Order.Status.RETURN_REQUESTED,Set.of(Order.Status.RETURN_APPROVED),Order.Status.RETURN_APPROVED,Set.of(Order.Status.RETURNED),Order.Status.RETURNED,Set.of(Order.Status.REFUNDED));if(!m.getOrDefault(from,Set.of()).contains(to))throw new IllegalArgumentException("Invalid order status transition: "+from+" -> "+to);}

 void restoreStock(Order o){for(Order.Item i:o.getItems()){if(i.getVariantId()==null)continue;Query q=new Query(Criteria.where("_id").is(i.getProductId()).and("variants.id").is(i.getVariantId()));Update u=new Update().inc("variants.$.stock",i.getQuantity());mongo.updateFirst(q,u,Product.class);}}
 public Product adminApprove(String id,boolean approved){Product p=products.findById(id).orElseThrow();p.setApproved(approved);p.setActive(approved);p.setUpdatedAt(Instant.now());return products.save(p);}public List<Product> all(){return products.findAll();}public List<Order> allOrders(){return orders.findAll();}
 public Coupon saveCoupon(CouponRequest r){Coupon c=coupons.findByCodeIgnoreCase(r.code()).orElse(Coupon.builder().build());c.setCode(req(r.code(),"Code required").toUpperCase());c.setName(r.name());c.setType(r.type());c.setValue(r.value());c.setMinOrder(r.minOrder());c.setMaxDiscount(r.maxDiscount());c.setValidFrom(r.validFrom());c.setValidTo(r.validTo());c.setUsageLimit(r.usageLimit());c.setActive(r.active());c.setVendorIds(r.vendorIds());return coupons.save(c);}public List<Coupon> coupons(){return coupons.findAll();}
 Coupon validCoupon(String code,String vendorId){if(code==null||code.isBlank())return null;Coupon c=coupons.findByCodeIgnoreCase(code).orElseThrow(()->new IllegalArgumentException("Invalid coupon"));Instant n=Instant.now();if(!c.isActive()||(c.getValidFrom()!=null&&n.isBefore(c.getValidFrom()))||(c.getValidTo()!=null&&n.isAfter(c.getValidTo()))||(c.getUsageLimit()>0&&c.getUsedCount()>=c.getUsageLimit())||(c.getVendorIds()!=null&&!c.getVendorIds().isEmpty()&&!c.getVendorIds().contains(vendorId)))throw new IllegalArgumentException("Coupon is not currently applicable");return c;}
 double discount(Coupon c,double amount){if(c==null||amount<c.getMinOrder())return 0;double d="PERCENTAGE".equalsIgnoreCase(c.getType())?amount*c.getValue()/100:c.getValue();return Math.min(amount, c.getMaxDiscount()>0?Math.min(d,c.getMaxDiscount()):d);}
 Product.Variant findVariant(Product p,String id){if(p.getVariants()==null||p.getVariants().isEmpty())return null;return p.getVariants().stream().filter(v->Objects.equals(v.getId(),id)).findFirst().orElseThrow(()->new IllegalArgumentException("Product variant not found"));}
 Order.Address address(AddressRequest r){return Order.Address.builder().name(r.name()).mobile(r.mobile()).line1(r.line1()).line2(r.line2()).area(r.area()).city(r.city()).state(r.state()).pincode(r.pincode()).landmark(r.landmark()).build();}
 User user(String e){return users.findByEmailIgnoreCase(e).orElseThrow();}Vendor vendor(String e){User u=user(e);return vendors.findByUserId(u.getId()).orElseThrow(()->new IllegalArgumentException("Vendor profile not found"));}String req(String x,String m){if(x==null||x.isBlank())throw new IllegalArgumentException(m);return x.trim();}
}
