import http from "./http";
export const createEnquiry = (payload) => http.post("/enquiries", null, { params: payload });
export const getMyEnquiries = () => http.get("/enquiries/my");
export const replyToEnquiry = (id, message) => http.post(`/enquiries/${id}/reply`, null, { params: { message } });
export const addFavorite = (postId) => http.post(`/favorites/${postId}`);
export const removeFavorite = (postId) => http.delete(`/favorites/${postId}`);
export const getFavorites = () => http.get("/favorites");
export const createReview = (payload) => http.post("/reviews", null, { params: payload });
export const getReviews = (postId) => http.get(`/reviews/post/${postId}`);
export const getNotifications = () => http.get("/notifications");
export const markNotificationRead = (id) => http.put(`/notifications/${id}/read`);
export const getConversations = () => http.get("/chat/conversations");
export const startConversation = (postId) => http.post("/chat/conversations", null, {params:{postId}});
export const startDirectChat = (userId) => http.post("/chat/direct", null, {params:{userId}});
export const createGroupChat = (payload) => http.post("/chat/groups", payload);
export const searchChatUsers = (q="") => http.get("/chat/users", {params:{q}});
export const getChatMembers = (id) => http.get(`/chat/${id}/members`);
export const addChatMember = (id,userId) => http.post(`/chat/${id}/members`, {userId});
export const removeChatMember = (id,userId) => http.delete(`/chat/${id}/members/${userId}`);
export const leaveChatGroup = (id) => http.post(`/chat/${id}/leave`);
export const getMessages = (id) => http.get(`/chat/${id}/messages`);
export const sendMessage = (id,payload) => http.post(`/chat/${id}/messages`, payload);
export const markChatRead = (id) => http.post(`/chat/${id}/read`);
export const searchChatMessages = (id,q) => http.get(`/chat/${id}/messages/search`, {params:{q}});
export const deleteChatMessage = (id,messageId) => http.delete(`/chat/${id}/messages/${messageId}`);
