package com.asmj.marketplace.printout.service;
import com.asmj.marketplace.printout.dto.PrintoutDtos.*; import com.asmj.marketplace.printout.model.PrintoutService; import com.asmj.marketplace.printout.repository.PrintoutServiceRepository; import com.asmj.marketplace.user.repository.UserRepository; import com.asmj.marketplace.vendor.repository.VendorRepository; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import java.math.BigDecimal; import java.time.Instant; import java.util.*;
@Service @RequiredArgsConstructor public class PrintoutServiceManager { private final PrintoutServiceRepository repo; private final UserRepository users; private final VendorRepository vendors;
 private String uid(String email){return users.findByEmailIgnoreCase(email).orElseThrow().getId();}
 public List<PrintoutService> publicServices(){return repo.findByActiveTrueOrderByCreatedAtDesc();}
 public List<PrintoutService> mine(String email){String vendorId=vendors.findByUserId(uid(email)).orElseThrow(()->new IllegalArgumentException("Vendor profile not found")).getId();return repo.findByVendorIdOrderByCreatedAtDesc(vendorId);}
 public PrintoutService save(String email,ServiceRequest r,String id){var v=vendors.findByUserId(uid(email)).orElseThrow(()->new IllegalArgumentException("Vendor profile not found")); var x=id==null?new PrintoutService():repo.findById(id).orElseThrow(()->new IllegalArgumentException("Printout service not found")); if(id!=null&&!v.getId().equals(x.getVendorId()))throw new IllegalArgumentException("You cannot update this printout service"); x.setVendorId(v.getId()); x.setServiceName(r.serviceName());x.setDescription(r.description());x.setPickupAvailable(Boolean.TRUE.equals(r.pickupAvailable()));x.setHomeDeliveryAvailable(Boolean.TRUE.equals(r.homeDeliveryAvailable()));x.setMinimumHomeDeliveryAmount(n(r.minimumHomeDeliveryAmount(),new BigDecimal("100")));x.setHomeDeliveryChargePercent(n(r.homeDeliveryChargePercent(),new BigDecimal("10")));x.setBwSingleRate(n(r.bwSingleRate(),BigDecimal.ZERO));x.setBwDoubleRate(n(r.bwDoubleRate(),BigDecimal.ZERO));x.setColorSingleRate(n(r.colorSingleRate(),BigDecimal.ZERO));x.setColorDoubleRate(n(r.colorDoubleRate(),BigDecimal.ZERO));x.setA3AdditionalCharge(n(r.a3AdditionalCharge(),BigDecimal.ZERO));x.setBindingCharge(n(r.bindingCharge(),BigDecimal.ZERO));x.setLaminationCharge(n(r.laminationCharge(),BigDecimal.ZERO));x.setActive(true);if(x.getCreatedAt()==null)x.setCreatedAt(Instant.now());x.setUpdatedAt(Instant.now());return repo.save(x); }
 private BigDecimal n(BigDecimal x,BigDecimal d){return x==null?d:x;}
 public void delete(String email,String id){var x=repo.findById(id).orElseThrow(()->new IllegalArgumentException("Printout service not found"));String vendorId=vendors.findByUserId(uid(email)).orElseThrow(()->new IllegalArgumentException("Vendor profile not found")).getId();if(!vendorId.equals(x.getVendorId()))throw new IllegalArgumentException("Not your service");repo.delete(x);}
}
