package com.asmj.marketplace.rental.config;

import com.asmj.marketplace.rental.location.*;import com.asmj.marketplace.rental.route.*;import com.asmj.marketplace.rental.vehicle.*;import com.asmj.marketplace.rental.fare.*;import com.asmj.marketplace.user.model.User;import com.asmj.marketplace.user.repository.UserRepository;import com.asmj.marketplace.vendor.repository.VendorRepository;
import lombok.RequiredArgsConstructor;import org.springframework.beans.factory.annotation.Value;import org.springframework.boot.CommandLineRunner;import org.springframework.context.annotation.Bean;import org.springframework.context.annotation.Configuration;import org.springframework.security.crypto.password.PasswordEncoder;import java.time.*;import java.util.*;
@Configuration @RequiredArgsConstructor
public class RentalDataSeeder {
 private final LocationRepository locations;private final RentalRouteRepository routes;private final VehicleRepository vehicles;private final DriverRepository drivers;private final FareRuleRepository fares;private final DiscountRuleRepository discounts;private final UserRepository users;private final VendorRepository vendors;private final PasswordEncoder passwordEncoder;@Value("${app.seed.enabled:${APP_SEED_ENABLED:true}}") private boolean enabled;
 @Bean CommandLineRunner seedRentals(){return args->{if(!enabled)return; if(locations.count()>0)return; Instant now=Instant.now();Map<String,LocationMaster> m=new LinkedHashMap<>(); add(m,"KA","Karnataka","Bengaluru",true,true,true,true);add(m,"KA","Karnataka","Mysuru",false,true,false,true);add(m,"TN","Tamil Nadu","Chennai",true,true,true,true);add(m,"TN","Tamil Nadu","Coimbatore",true,true,true,true);add(m,"TS","Telangana","Hyderabad",true,true,true,true);add(m,"MH","Maharashtra","Mumbai",true,true,true,true);add(m,"MH","Maharashtra","Pune",true,true,true,true);add(m,"KL","Kerala","Kochi",true,true,true,true);add(m,"GA","Goa","Panaji",true,true,true,true);add(m,"DL","Delhi","New Delhi",true,true,true,true);add(m,"RJ","Rajasthan","Jaipur",true,true,true,true);m.values().forEach(locations::save);
  route(m.get("Bengaluru"),m.get("Mysuru"),145);route(m.get("Bengaluru"),m.get("Chennai"),350);route(m.get("Bengaluru"),m.get("Hyderabad"),570);route(m.get("Bengaluru"),m.get("Mumbai"),980);route(m.get("Bengaluru"),m.get("Pune"),840);route(m.get("Bengaluru"),m.get("Coimbatore"),365);route(m.get("Chennai"),m.get("Bengaluru"),350);route(m.get("Hyderabad"),m.get("Bengaluru"),570);route(m.get("Mumbai"),m.get("Pune"),150);route(m.get("Kochi"),m.get("Bengaluru"),545);route(m.get("Bengaluru"),m.get("Panaji"),590);
  fares.save(FareRule.builder().name("Sedan One Way").vehicleType("SEDAN").journeyType("ONE_WAY").baseFare(1800).includedKm(150).extraKmRate(14).driverAllowance(300).nightCharge(250).taxRate(5).priority(10).active(true).build());
  fares.save(FareRule.builder().name("Sedan Round Trip").vehicleType("SEDAN").journeyType("ROUND_TRIP").baseFare(3200).includedKm(300).extraKmRate(12).driverAllowance(600).nightCharge(250).taxRate(5).priority(10).active(true).build());
  fares.save(FareRule.builder().name("SUV One Way").vehicleType("SUV").journeyType("ONE_WAY").baseFare(2500).includedKm(150).extraKmRate(18).driverAllowance(350).nightCharge(300).taxRate(5).priority(10).active(true).build());
  discounts.save(DiscountRule.builder().code("WELCOME10").name("Welcome 10%").type("PERCENTAGE").value(10).maxDiscount(1000).minFare(1000).active(true).build());
  discounts.save(DiscountRule.builder().code("SAVE500").name("Flat ₹500").type("FIXED").value(500).maxDiscount(500).minFare(3000).active(true).build());
  vendors.findByUserId(users.findByEmailIgnoreCase("demo.rentals@asmj.co.in").map(User::getId).orElse("")).ifPresent(v->{Vehicle car=vehicles.save(Vehicle.builder().vendorId(v.getId()).registrationNumber("KA01AB1234").vehicleType("SEDAN").make("Maruti").model("Dzire").year(2024).seats(4).fuelType("PETROL").transmission("MANUAL").ac(true).currentKm(18500).status(Vehicle.Status.AVAILABLE).insuranceNumber("DEMO-INS-001").insuranceExpiry(LocalDate.now().plusYears(1)).permitNumber("DEMO-PERMIT-001").permitType("ALL_INDIA_TOURIST").permitIssuingState("Karnataka").permitExpiry(LocalDate.now().plusYears(1)).coveredStates(new HashSet<>(List.of("KA","TN","TS","MH","KL","GA","DL","RJ"))).createdAt(now).updatedAt(now).build());User du=users.findByEmailIgnoreCase("demo.driver@asmj.co.in").orElseGet(()->users.save(User.builder().name("Demo Driver").email("demo.driver@asmj.co.in").mobile("9000000011").password(passwordEncoder.encode("Demo@12345")).roles(Set.of(User.Role.DRIVER)).status(User.Status.ACTIVE).createdAt(now).updatedAt(now).build()));drivers.save(Driver.builder().userId(du.getId()).vendorId(v.getId()).name(du.getName()).mobile(du.getMobile()).licenseNumber("KA-DRV-DEMO-001").licenseType("LMV-TR").licenseExpiry(LocalDate.now().plusYears(2)).assignedVehicleId(car.getId()).status(Driver.Status.ACTIVE).createdAt(now).updatedAt(now).build());});
 };}
 private void add(Map<String,LocationMaster> m,String code,String state,String city,boolean origin,boolean dest,boolean airport,boolean railway){m.put(city,LocationMaster.builder().stateCode(code).stateName(state).cityName(city).slug((state+"-"+city).toLowerCase().replaceAll("[^a-z0-9]+","-")).originAllowed(origin).destinationAllowed(dest).airport(airport).railway(railway).localPickup(true).active(true).createdAt(Instant.now()).updatedAt(Instant.now()).build());}
 private void route(LocationMaster f,LocationMaster t,double km){routes.save(RentalRoute.builder().fromLocationId(f.getId()).toLocationId(t.getId()).fromStateCode(f.getStateCode()).fromState(f.getStateName()).fromCity(f.getCityName()).toStateCode(t.getStateCode()).toState(t.getStateName()).toCity(t.getCityName()).interstate(!f.getStateCode().equalsIgnoreCase(t.getStateCode())).oneWayAllowed(true).roundTripAllowed(true).estimatedKm(km).minKm(km*.85).maxKm(km*1.25).estimatedMinutes((long)(km/55*60)).active(true).createdAt(Instant.now()).updatedAt(Instant.now()).build());}
}
