package com.asmj.marketplace.rental.booking;

import com.asmj.marketplace.common.model.StatusHistory;
import com.asmj.marketplace.notification.service.NotificationService;
import com.asmj.marketplace.rental.audit.*;
import com.asmj.marketplace.rental.fare.*;
import com.asmj.marketplace.rental.location.*;
import com.asmj.marketplace.rental.route.*;
import com.asmj.marketplace.rental.vehicle.*;
import com.asmj.marketplace.user.model.User;
import com.asmj.marketplace.user.repository.UserRepository;
import com.asmj.marketplace.vendor.model.Vendor;
import com.asmj.marketplace.vendor.repository.VendorRepository;
import lombok.RequiredArgsConstructor;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.security.crypto.password.PasswordEncoder;
import org.springframework.stereotype.Service;
import java.time.*;
import java.util.*;

@Service @RequiredArgsConstructor
public class RentalService {
 private final LocationRepository locations; private final RentalRouteRepository routes; private final VehicleRepository vehicles; private final DriverRepository drivers;
 private final FareRuleRepository fares; private final DiscountRuleRepository discounts; private final RentalBookingRepository bookings; private final RentalAuditRepository audits;
 private final UserRepository users; private final VendorRepository vendors; private final NotificationService notifications; private final PasswordEncoder encoder;
 @Value("${rental.max-km-per-hour:120}") private double maxKmPerHour;

 public List<LocationMaster> locations(){return locations.findByActiveTrueOrderByStateNameAscCityNameAsc();}
 public List<RentalRoute> routes(){return routes.findByActiveTrueOrderByFromStateAscFromCityAscToCityAsc();}
 public RentalRoute route(String from,String to){return routes.findByFromLocationIdAndToLocationId(from,to).filter(RentalRoute::isActive).orElseThrow(()->new IllegalArgumentException("This origin/destination route is not configured"));}

 public Map<String,Object> quote(RentalDtos.QuoteRequest q){
  RentalBooking.JourneyType journey=q.journeyType()==null?RentalBooking.JourneyType.ONE_WAY:q.journeyType();
  RentalRoute route=route(q.fromLocationId(),q.toLocationId());
  validateJourney(route,journey);
  String vehicleType=required(q.vehicleType(),"Vehicle type is required");
  double km=q.estimatedKm()!=null&&q.estimatedKm()>0?q.estimatedKm():route.getEstimatedKm(); if(journey==RentalBooking.JourneyType.ROUND_TRIP) km*=2;
  FareRule rule=findFare(route.getId(),vehicleType,journey);
  RentalBooking.FareBreakdown b=calculate(rule,km,q.travelDate(),q.pickupTime(),0,0,0,q.discountCode());
  return new LinkedHashMap<>(Map.of("route",route,"fare",b,"vehicleType",vehicleType,"journeyType",journey,"estimatedKm",km));
 }

 public RentalBooking create(String email,RentalDtos.BookingRequest r){
  User u=user(email); RentalBooking.JourneyType journey=r.journeyType()==null?RentalBooking.JourneyType.ONE_WAY:r.journeyType(); RentalRoute route=route(r.fromLocationId(),r.toLocationId()); validateJourney(route,journey);
  validateAddress(r.pickupAddress(),"Full pickup address is required"); validateAddress(r.dropAddress(),"Full drop address is required");
  if(r.travelDate()==null||r.pickupTime()==null) throw new IllegalArgumentException("Travel date and pickup time are required");
  if(journey==RentalBooking.JourneyType.ROUND_TRIP && (r.returnDate()==null||r.returnTime()==null)) throw new IllegalArgumentException("Return date and time are required for a round trip");
  int pax=r.passengerCount()==null?1:r.passengerCount(); if(pax<1)throw new IllegalArgumentException("Passenger count must be at least 1");
  Vehicle vehicle=resolveVehicle(r.vehicleId(),r.vehicleType(),pax); Vendor vendor=vendorForVehicle(vehicle); validateVehicleForRoute(vehicle,route); Driver driver=null;
  if(r.driverId()!=null&&!r.driverId().isBlank()) driver=drivers.findById(r.driverId()).orElseThrow(()->new IllegalArgumentException("Driver not found"));
  if(driver!=null){if(!Objects.equals(driver.getVendorId(),vendor.getId()))throw new IllegalArgumentException("Driver does not belong to this vendor");validateDriver(driver);}
  FareRule fr=findFare(route.getId(),vehicle.getVehicleType(),journey);
  double km=route.getEstimatedKm()*(journey==RentalBooking.JourneyType.ROUND_TRIP?2:1);
  RentalBooking.FareBreakdown breakdown=calculate(fr,km,r.travelDate(),r.pickupTime(),0,0,0,r.discountCode());
  Instant now=Instant.now(); RentalBooking b=RentalBooking.builder().bookingNumber("ASMJ-R"+String.format("%08d",Math.abs(UUID.randomUUID().hashCode()))).customerId(u.getId()).vendorId(vendor.getId()).vehicleId(vehicle.getId()).driverId(driver==null?null:driver.getId()).routeId(route.getId())
   .fromLocationId(route.getFromLocationId()).toLocationId(route.getToLocationId()).fromStateCode(route.getFromStateCode()).fromState(route.getFromState()).fromCity(route.getFromCity()).toStateCode(route.getToStateCode()).toState(route.getToState()).toCity(route.getToCity()).journeyType(journey)
   .pickupAddress(r.pickupAddress().trim()).pickupLandmark(r.pickupLandmark()).dropAddress(r.dropAddress().trim()).dropLandmark(r.dropLandmark()).travelDate(r.travelDate()).pickupTime(r.pickupTime()).returnDate(r.returnDate()).returnTime(r.returnTime())
   .passengerCount(pax).luggageCount(r.luggageCount()==null?0:Math.max(0,r.luggageCount())).customerName(u.getName()).customerMobile(u.getMobile()).customerEmail(u.getEmail()).notes(r.notes()).status(RentalBooking.Status.REQUESTED)
   .estimatedFare(breakdown.getFinalAmount()).fareBreakdown(breakdown).discountCode(r.discountCode()).createdAt(now).updatedAt(now).build();
  if(driver!=null)b.setStatus(RentalBooking.Status.DRIVER_ASSIGNED);
  b.getStatusHistory().add(history(b.getStatus().name(),u,"Rental booking created",now));
  RentalBooking saved=bookings.save(b); audit("BOOKING",saved.getId(),"CREATE",u,"",saved.getStatus().name(),"Customer booking");
  notifyUsers(vendor.getUserId(),"New rental booking","Booking "+saved.getBookingNumber()+" has been requested.","RENTAL_BOOKING");
  if(driver!=null)notifyUsers(driverUser(driver),"Trip assigned","You have been assigned booking "+saved.getBookingNumber()+".","RENTAL_DRIVER");
  return saved;
 }

 public List<RentalBooking> mine(String email){return bookings.findByCustomerIdOrderByCreatedAtDesc(user(email).getId());}
 public List<RentalBooking> vendorBookings(String email){Vendor v=vendor(email);return bookings.findByVendorIdOrderByCreatedAtDesc(v.getId());}
 public List<RentalBooking> driverTrips(String email){Driver d=drivers.findByUserId(user(email).getId()).orElseThrow(()->new IllegalArgumentException("Driver profile not found"));return bookings.findByDriverIdOrderByTravelDateAscPickupTimeAsc(d.getId());}
 public RentalBooking get(String email,String id){RentalBooking b=bookings.findById(id).orElseThrow(()->new IllegalArgumentException("Rental booking not found"));User u=user(email);boolean allowed=Objects.equals(b.getCustomerId(),u.getId())||u.getRoles().contains(User.Role.ADMIN);if(!allowed){Vendor v=vendors.findByUserId(u.getId()).orElse(null);Driver d=drivers.findByUserId(u.getId()).orElse(null);allowed=(v!=null&&Objects.equals(b.getVendorId(),v.getId()))||(d!=null&&Objects.equals(b.getDriverId(),d.getId()));}if(!allowed)throw new IllegalArgumentException("You cannot view this rental booking");return b;}

 public RentalBooking customerConfirm(String email,String id){User u=user(email);RentalBooking b=bookings.findById(id).orElseThrow();if(!Objects.equals(b.getCustomerId(),u.getId()))throw new IllegalArgumentException("You cannot confirm this booking");if(b.getStatus()!=RentalBooking.Status.VENDOR_CONFIRMED&&b.getStatus()!=RentalBooking.Status.DRIVER_ASSIGNED)throw new IllegalArgumentException("Booking is not ready for customer confirmation");change(b,RentalBooking.Status.CUSTOMER_CONFIRMED,u,"Customer confirmed booking");notifyDriver(b,"Customer confirmed booking");notifyUsers(b.getVendorId(),"Customer confirmed","Booking "+b.getBookingNumber()+" has been confirmed by the customer.","RENTAL_BOOKING");return bookings.save(b);}
 public RentalBooking cancelCustomer(String email,String id,String reason){User u=user(email);RentalBooking b=bookings.findById(id).orElseThrow();if(!Objects.equals(b.getCustomerId(),u.getId()))throw new IllegalArgumentException("You cannot cancel this booking");if(!EnumSet.of(RentalBooking.Status.REQUESTED,RentalBooking.Status.VENDOR_CONFIRMED,RentalBooking.Status.DRIVER_ASSIGNED,RentalBooking.Status.CUSTOMER_CONFIRMED,RentalBooking.Status.DRIVER_EN_ROUTE).contains(b.getStatus()))throw new IllegalArgumentException("Journey has started or booking is not cancellable; admin review required");b.setCancellationReason(reason);change(b,RentalBooking.Status.CANCELLED,u,reason==null?"Cancelled by customer":reason);releaseVehicle(b);vendors.findById(b.getVendorId()).ifPresent(v->notifyUsers(v.getUserId(),"Rental cancelled","Customer cancelled booking "+b.getBookingNumber()+".","RENTAL_BOOKING"));return bookings.save(b);}
 public RentalBooking driverStatus(String email,String id,RentalDtos.StatusRequest r){User u=user(email);Driver d=driver(email);RentalBooking b=driverOwned(id,d.getId());RentalBooking.Status next=parseStatus(r.status());if(next!=RentalBooking.Status.DRIVER_EN_ROUTE||!(b.getStatus()==RentalBooking.Status.DRIVER_ASSIGNED||b.getStatus()==RentalBooking.Status.CUSTOMER_CONFIRMED))throw new IllegalArgumentException("Invalid driver status transition");change(b,next,u,r.note()==null?"Driver is en route":r.note());notifyUsers(b.getCustomerId(),"Driver is en route","Your driver is on the way for booking "+b.getBookingNumber()+".","RENTAL_TRIP");return bookings.save(b);}

 public RentalBooking vendorStatus(String email,String id,RentalDtos.StatusRequest r){User u=user(email);Vendor v=vendor(email);RentalBooking b=owned(id,v.getId());RentalBooking.Status next=parseStatus(r.status());if(!allowedVendor(b.getStatus(),next))throw new IllegalArgumentException("Invalid rental status transition");change(b,next,u,r.note());if(next==RentalBooking.Status.VENDOR_CONFIRMED&&b.getDriverId()!=null)notifyDriver(b,"Booking confirmed");if(next==RentalBooking.Status.REJECTED||next==RentalBooking.Status.CANCELLED)releaseVehicle(b);audit("BOOKING",id,"STATUS",u,b.getStatus().name(),next.name(),r.note());return bookings.save(b);}

 public RentalBooking assign(String email,String id,String vehicleId,String driverId){User u=user(email);Vendor v=vendor(email);RentalBooking b=owned(id,v.getId());Vehicle vehicle=vehicles.findById(vehicleId).orElseThrow(()->new IllegalArgumentException("Vehicle not found"));if(!Objects.equals(vehicle.getVendorId(),v.getId()))throw new IllegalArgumentException("Vehicle does not belong to vendor");validateVehicleForRoute(vehicle,routes.findById(b.getRouteId()).orElseThrow());Driver driver=drivers.findById(driverId).orElseThrow(()->new IllegalArgumentException("Driver not found"));if(!Objects.equals(driver.getVendorId(),v.getId()))throw new IllegalArgumentException("Driver does not belong to vendor");validateDriver(driver);ensureAvailable(vehicle,driver);b.setVehicleId(vehicle.getId());b.setDriverId(driver.getId());change(b,RentalBooking.Status.DRIVER_ASSIGNED,u,"Vehicle and driver assigned");vehicle.setStatus(Vehicle.Status.BOOKED);vehicles.save(vehicle);notifyUsers(driverUser(driver),"Trip assigned","Booking "+b.getBookingNumber()+" has been assigned to you.","RENTAL_DRIVER");notifyUsers(b.getCustomerId(),"Driver assigned","A driver and vehicle have been assigned to booking "+b.getBookingNumber()+".","RENTAL_BOOKING");audit("BOOKING",id,"ASSIGN",u,"","DRIVER_ASSIGNED",vehicle.getRegistrationNumber());return bookings.save(b);}

 public RentalBooking start(String email,String id,RentalDtos.KmRequest r){User u=user(email);Driver d=driver(email);RentalBooking b=driverOwned(id,d.getId());if(b.getStatus()!=RentalBooking.Status.DRIVER_ASSIGNED&&b.getStatus()!=RentalBooking.Status.CUSTOMER_CONFIRMED&&b.getStatus()!=RentalBooking.Status.DRIVER_EN_ROUTE)throw new IllegalArgumentException("Journey cannot be started from "+b.getStatus());if(r.km()<0)throw new IllegalArgumentException("Starting KM cannot be negative");Vehicle v=vehicles.findById(b.getVehicleId()).orElseThrow();if(r.km()+0.001<v.getCurrentKm())throw new IllegalArgumentException("Starting KM cannot be less than the vehicle's current KM");validateTripTime(b,r.km(),null);b.setStartKm(r.km());b.setStartAt(Instant.now());b.setStartLat(r.lat());b.setStartLng(r.lng());change(b,RentalBooking.Status.JOURNEY_STARTED,u,"Journey started at KM "+r.km());v.setStatus(Vehicle.Status.ON_TRIP);v.setCurrentKm(r.km());vehicles.save(v);notifyUsers(b.getCustomerId(),"Journey started","Driver has started booking "+b.getBookingNumber()+" at KM "+r.km()+".","RENTAL_TRIP");audit("BOOKING",id,"START",u,"","JOURNEY_STARTED","Start KM "+r.km());return bookings.save(b);}

 public RentalBooking outboundEnd(String email,String id,RentalDtos.KmRequest r){User u=user(email);Driver d=driver(email);RentalBooking b=driverOwned(id,d.getId());if(b.getJourneyType()!=RentalBooking.JourneyType.ROUND_TRIP)throw new IllegalArgumentException("Outbound-end is only for round trips");if(b.getStatus()!=RentalBooking.Status.JOURNEY_STARTED&&b.getStatus()!=RentalBooking.Status.JOURNEY_IN_PROGRESS)throw new IllegalArgumentException("Outbound journey is not active");ensureEndKm(b.getStartKm(),r.km());b.setOutboundEndKm(r.km());b.setOutboundEndAt(Instant.now());Vehicle v=vehicles.findById(b.getVehicleId()).orElseThrow();v.setCurrentKm(r.km());vehicles.save(v);change(b,RentalBooking.Status.OUTBOUND_COMPLETED,u,"Outbound journey ended at KM "+r.km());notifyUsers(b.getCustomerId(),"Outbound journey completed","Outbound leg of "+b.getBookingNumber()+" ended at KM "+r.km()+".","RENTAL_TRIP");return bookings.save(b);}
 public RentalBooking returnStart(String email,String id,RentalDtos.KmRequest r){User u=user(email);Driver d=driver(email);RentalBooking b=driverOwned(id,d.getId());if(b.getJourneyType()!=RentalBooking.JourneyType.ROUND_TRIP||b.getStatus()!=RentalBooking.Status.OUTBOUND_COMPLETED)throw new IllegalArgumentException("Return journey cannot be started now");ensureEndKm(b.getOutboundEndKm(),r.km());b.setReturnStartKm(r.km());b.setReturnStartAt(Instant.now());change(b,RentalBooking.Status.RETURN_STARTED,u,"Return journey started at KM "+r.km());notifyUsers(b.getCustomerId(),"Return journey started","Return leg of "+b.getBookingNumber()+" has started.","RENTAL_TRIP");return bookings.save(b);}
 public RentalBooking end(String email,String id,RentalDtos.KmRequest r){User u=user(email);Driver d=driver(email);RentalBooking b=driverOwned(id,d.getId());if(b.getStatus()!=RentalBooking.Status.JOURNEY_STARTED&&b.getStatus()!=RentalBooking.Status.JOURNEY_IN_PROGRESS&&b.getStatus()!=RentalBooking.Status.RETURN_STARTED)throw new IllegalArgumentException("Journey is not active");Double lower=b.getJourneyType()==RentalBooking.JourneyType.ROUND_TRIP?b.getReturnStartKm():b.getStartKm();ensureEndKm(lower,r.km());validateTripTime(b,b.getStartKm(),r.km());b.setEndKm(r.km());b.setEndAt(Instant.now());b.setEndLat(r.lat());b.setEndLng(r.lng());b.setToll(nvl(r.toll()));b.setParking(nvl(r.parking()));b.setOtherCharges(nvl(r.otherCharges()));double actual;if(b.getJourneyType()==RentalBooking.JourneyType.ROUND_TRIP)actual=(b.getOutboundEndKm()-b.getStartKm())+(b.getEndKm()-b.getReturnStartKm());else actual=b.getEndKm()-b.getStartKm();b.setActualKm(actual);RentalRoute route=routes.findById(b.getRouteId()).orElseThrow();FareRule fr=findFare(route.getId(),vehicles.findById(b.getVehicleId()).orElseThrow().getVehicleType(),b.getJourneyType());RentalBooking.FareBreakdown fb=calculate(fr,actual,b.getTravelDate(),b.getPickupTime(),nvl(b.getToll()),nvl(b.getParking()),nvl(b.getOtherCharges()),b.getDiscountCode());b.setFareBreakdown(fb);b.setFinalFare(fb.getFinalAmount());change(b,RentalBooking.Status.JOURNEY_COMPLETED,u,"Journey completed at KM "+r.km()+"; actual KM "+actual);change(b,RentalBooking.Status.FARE_FINALIZED,u,"Final fare calculated from actual KM");Vehicle v=vehicles.findById(b.getVehicleId()).orElseThrow();v.setCurrentKm(b.getEndKm());v.setStatus(Vehicle.Status.AVAILABLE);vehicles.save(v);notifyUsers(b.getCustomerId(),"Journey completed","Booking "+b.getBookingNumber()+" completed. Final fare: ₹"+String.format(Locale.US,"%.2f",b.getFinalFare()),"RENTAL_FARE");audit("BOOKING",id,"END",u,"","FARE_FINALIZED","End KM "+r.km()+", actual KM "+actual);return bookings.save(b);}

 public List<Vehicle> publicVehicles(String q,String vehicleType){
  String search=q==null?"":q.trim().toLowerCase();
  String type=vehicleType==null?"":vehicleType.trim();
  return vehicles.findByStatusOrderByCreatedAtDesc(Vehicle.Status.AVAILABLE).stream()
    .filter(v->{
      if(type.isBlank()) return true;
      return v.getVehicleType()!=null && v.getVehicleType().equalsIgnoreCase(type);
    })
    .filter(v->{
      if(search.isBlank()) return true;
      String hay=String.join(" ",Objects.toString(v.getRegistrationNumber(),""),Objects.toString(v.getVehicleType(),""),Objects.toString(v.getMake(),""),Objects.toString(v.getModel(),""));
      return hay.toLowerCase().contains(search);
    })
    .filter(v->vendors.findById(v.getVendorId()).map(x->x.getVerificationStatus()==Vendor.VerificationStatus.APPROVED && x.getStatus()==Vendor.Status.ACTIVE).orElse(false))
    .toList();
 }
 public List<Vehicle> vendorVehicles(String email){return vehicles.findByVendorIdOrderByCreatedAtDesc(vendor(email).getId());}
 public Vehicle saveVehicle(String email,Vehicle input){Vendor v=vendor(email);if(input.getId()!=null&& !input.getId().isBlank()){Vehicle x=vehicles.findById(input.getId()).orElseThrow();if(!Objects.equals(x.getVendorId(),v.getId()))throw new IllegalArgumentException("Vehicle not owned by vendor");input.setVendorId(v.getId());input.setUpdatedAt(Instant.now());return vehicles.save(input);}if(input.getRegistrationNumber()==null||input.getRegistrationNumber().isBlank())throw new IllegalArgumentException("Registration number is required");if(vehicles.existsByRegistrationNumberIgnoreCase(input.getRegistrationNumber()))throw new IllegalArgumentException("Registration number already exists");input.setVendorId(v.getId());input.setStatus(Vehicle.Status.AVAILABLE);input.setCreatedAt(Instant.now());input.setUpdatedAt(Instant.now());return vehicles.save(input);}
 public void deleteVehicle(String email,String id){Vendor v=vendor(email);Vehicle x=vehicles.findById(id).orElseThrow();if(!Objects.equals(x.getVendorId(),v.getId()))throw new IllegalArgumentException("Vehicle not owned by vendor");if(x.getStatus()==Vehicle.Status.ON_TRIP||x.getStatus()==Vehicle.Status.BOOKED)throw new IllegalArgumentException("Busy vehicle cannot be deleted");vehicles.delete(x);}
 public List<Driver> vendorDrivers(String email){return drivers.findByVendorIdOrderByCreatedAtDesc(vendor(email).getId());}
 public Driver createDriver(String email,RentalDtos.DriverRequest r){Vendor v=vendor(email);if(r.email()==null||r.password()==null||r.password().length()<8)throw new IllegalArgumentException("Driver email and password (minimum 8 characters) are required");if(users.existsByEmailIgnoreCase(r.email()))throw new IllegalArgumentException("Email already registered");User u=User.builder().name(required(r.name(),"Driver name is required")).email(r.email().trim().toLowerCase()).mobile(r.mobile()).password(encoder.encode(r.password())).roles(Set.of(User.Role.DRIVER)).status(User.Status.ACTIVE).createdAt(Instant.now()).updatedAt(Instant.now()).build();users.save(u);Driver d=Driver.builder().userId(u.getId()).vendorId(v.getId()).name(u.getName()).mobile(r.mobile()).licenseNumber(r.licenseNumber()).licenseType(r.licenseType()).licenseExpiry(r.licenseExpiry()).assignedVehicleId(r.assignedVehicleId()).documents(r.documents()==null?new ArrayList<>():r.documents()).createdAt(Instant.now()).updatedAt(Instant.now()).build();validateDriver(d);return drivers.save(d);}
 public Driver updateDriver(String email,String id,RentalDtos.DriverRequest r){Vendor v=vendor(email);Driver d=drivers.findById(id).orElseThrow();if(!Objects.equals(d.getVendorId(),v.getId()))throw new IllegalArgumentException("Driver not owned by vendor");d.setName(r.name());d.setMobile(r.mobile());d.setLicenseNumber(r.licenseNumber());d.setLicenseType(r.licenseType());d.setLicenseExpiry(r.licenseExpiry());d.setAssignedVehicleId(r.assignedVehicleId());d.setDocuments(r.documents()==null?d.getDocuments():r.documents());d.setUpdatedAt(Instant.now());validateDriver(d);return drivers.save(d);}
 public List<RentalBooking> adminBookings(String email){if(!user(email).getRoles().contains(User.Role.ADMIN))throw new IllegalArgumentException("Admin access required");return bookings.findAll();}
 public <T> T adminSave(T o){return o;}
 public List<LocationMaster> adminLocations(String email){admin(email);return locations.findAll();}
 public LocationMaster saveLocation(String email,LocationMaster x){admin(email);if(x.getSlug()==null||x.getSlug().isBlank())x.setSlug((x.getStateName()+"-"+x.getCityName()).toLowerCase().replaceAll("[^a-z0-9]+","-"));if(x.getCreatedAt()==null)x.setCreatedAt(Instant.now());x.setUpdatedAt(Instant.now());return locations.save(x);}
 public void deleteLocation(String email,String id){admin(email);locations.deleteById(id);}
 public List<RentalRoute> adminRoutes(String email){admin(email);return routes.findAll();}
 public RentalRoute saveRoute(String email,RentalRoute x){admin(email);LocationMaster f=locations.findById(x.getFromLocationId()).orElseThrow();LocationMaster t=locations.findById(x.getToLocationId()).orElseThrow();x.setFromStateCode(f.getStateCode());x.setFromState(f.getStateName());x.setFromCity(f.getCityName());x.setToStateCode(t.getStateCode());x.setToState(t.getStateName());x.setToCity(t.getCityName());x.setInterstate(!(f.getStateCode()!=null) && t.getStateCode()!=null && f.getStateCode().equalsIgnoreCase(t.getStateCode()));if(x.getCreatedAt()==null)x.setCreatedAt(Instant.now());x.setUpdatedAt(Instant.now());return routes.save(x);}
 public void deleteRoute(String email,String id){admin(email);routes.deleteById(id);}
 public List<FareRule> adminFares(String email){admin(email);return fares.findAll();}
 public FareRule saveFare(String email,FareRule x){admin(email);if(x.getValidFrom()==null)x.setValidFrom(Instant.now());return fares.save(x);}
 public void deleteFare(String email,String id){admin(email);fares.deleteById(id);}
 public List<DiscountRule> adminDiscounts(String email){admin(email);return discounts.findAll();}
 public DiscountRule saveDiscount(String email,DiscountRule x){admin(email);return discounts.save(x);}
 public void deleteDiscount(String email,String id){admin(email);discounts.deleteById(id);}
 public List<RentalAudit> audits(String email,String entityId){admin(email);return audits.findByEntityIdOrderByCreatedAtDesc(entityId);}

 private FareRule findFare(String routeId,String vehicleType,RentalBooking.JourneyType jt){Instant now=Instant.now();return fares.findByActiveTrueOrderByPriorityDesc().stream().filter(f->f.getVehicleType()!=null && vehicleType!=null && f.getVehicleType().equalsIgnoreCase(vehicleType)).filter(f->f.getJourneyType()==null||f.getJourneyType().isBlank()||f.getJourneyType().equalsIgnoreCase(jt.name())).filter(f->f.getRouteId()==null||f.getRouteId().isBlank()||Objects.equals(f.getRouteId(),routeId)).filter(f->f.getValidFrom()==null||!now.isBefore(f.getValidFrom())).filter(f->f.getValidTo()==null||!now.isAfter(f.getValidTo())).findFirst().orElseThrow(()->new IllegalArgumentException("No active fare rule configured for "+vehicleType));}
 private RentalBooking.FareBreakdown calculate(FareRule f,double km,LocalDate date,LocalTime time,double toll,double parking,double other,String code){double extra=Math.max(0,km-f.getIncludedKm());double extraCharge=extra*f.getExtraKmRate();double night=isNight(time)?f.getNightCharge():0;double driver=f.getDriverAllowance();double gross=f.getBaseFare()+extraCharge+driver+night+(f.getTollMode()==FareRule.ChargeMode.ACTUAL?toll:0)+(f.getParkingMode()==FareRule.ChargeMode.ACTUAL?parking:0)+other;double discount=discount(code,gross);double taxable=Math.max(0,gross-discount);double tax=taxable*f.getTaxRate()/100d;double finalAmount=taxable+tax;return RentalBooking.FareBreakdown.builder().baseFare(f.getBaseFare()).includedKm(f.getIncludedKm()).actualKm(km).extraKm(extra).extraKmCharge(extraCharge).driverAllowance(driver).nightCharge(night).toll(toll).parking(parking).otherCharges(other).gross(gross).discount(discount).taxableAmount(taxable).tax(tax).finalAmount(Math.max(0,finalAmount)).build();}
 private double discount(String code,double gross){if(code==null||code.isBlank())return 0;DiscountRule d=discounts.findByCodeIgnoreCase(code.trim()).orElseThrow(()->new IllegalArgumentException("Invalid discount code"));Instant now=Instant.now();if(!d.isActive()||(d.getValidFrom()!=null&&now.isBefore(d.getValidFrom()))||(d.getValidTo()!=null&&now.isAfter(d.getValidTo()))||gross<d.getMinFare())throw new IllegalArgumentException("Discount code is not currently applicable");double value="PERCENTAGE".equalsIgnoreCase(d.getType())?gross*d.getValue()/100d:d.getValue();return Math.min(value,d.getMaxDiscount()>0?d.getMaxDiscount():value);}
 private boolean isNight(LocalTime t){return t!=null&&(t.isBefore(LocalTime.of(6,0))||!t.isBefore(LocalTime.of(22,0)));}
 private void validateJourney(RentalRoute r,RentalBooking.JourneyType j){if(j==RentalBooking.JourneyType.ONE_WAY&&!r.isOneWayAllowed())throw new IllegalArgumentException("One-way journey is not available on this route");if(j==RentalBooking.JourneyType.ROUND_TRIP&&!r.isRoundTripAllowed())throw new IllegalArgumentException("Round trip is not available on this route");}
 private Vehicle resolveVehicle(String id,String type,int pax){Vehicle v;if(id!=null&&!id.isBlank())v=vehicles.findById(id).orElseThrow(()->new IllegalArgumentException("Vehicle not found"));else{v=vehicles.findByStatusAndVehicleType(Vehicle.Status.AVAILABLE,required(type,"Vehicle type is required")).stream().findFirst().orElseThrow(()->new IllegalArgumentException("No available vehicle of this type"));}if(v.getSeats()!=null&&v.getSeats()<pax)throw new IllegalArgumentException("Selected vehicle cannot accommodate all passengers");ensureAvailable(v,null);return v;}
 private void ensureAvailable(Vehicle v,Driver d){if(v.getStatus()!=Vehicle.Status.AVAILABLE)throw new IllegalArgumentException("Vehicle is not available");if(bookings.existsByVehicleIdAndStatusIn(v.getId(),activeStatuses()))throw new IllegalArgumentException("Vehicle already has an active booking");if(d!=null&&bookings.existsByDriverIdAndStatusIn(d.getId(),activeStatuses()))throw new IllegalArgumentException("Driver already has an active booking");}
 private Set<RentalBooking.Status> activeStatuses(){return EnumSet.of(RentalBooking.Status.REQUESTED,RentalBooking.Status.VENDOR_CONFIRMED,RentalBooking.Status.DRIVER_ASSIGNED,RentalBooking.Status.CUSTOMER_CONFIRMED,RentalBooking.Status.DRIVER_EN_ROUTE,RentalBooking.Status.JOURNEY_STARTED,RentalBooking.Status.JOURNEY_IN_PROGRESS,RentalBooking.Status.OUTBOUND_COMPLETED,RentalBooking.Status.RETURN_STARTED);}
 private Vendor vendorForVehicle(Vehicle v){return vendors.findById(v.getVendorId()).filter(x->x.getVerificationStatus()==Vendor.VerificationStatus.APPROVED&&x.getStatus()==Vendor.Status.ACTIVE).orElseThrow(()->new IllegalArgumentException("Vehicle vendor is not approved/active"));}
 private Vendor vendor(String email){User u=user(email);return vendors.findByUserId(u.getId()).filter(v->v.getVerificationStatus()==Vendor.VerificationStatus.APPROVED&&v.getStatus()==Vendor.Status.ACTIVE).orElseThrow(()->new IllegalArgumentException("Approved vendor profile required"));}
 private User user(String email){return users.findByEmailIgnoreCase(email).orElseThrow(()->new IllegalArgumentException("User not found"));}
 private Driver driver(String email){return drivers.findByUserId(user(email).getId()).orElseThrow(()->new IllegalArgumentException("Driver profile not found"));}
 private String driverUser(Driver d){return d.getUserId();}
 private void validateDriver(Driver d){if(d.getStatus()!=Driver.Status.ACTIVE)throw new IllegalArgumentException("Driver is not active");if(d.getLicenseExpiry()==null||d.getLicenseExpiry().isBefore(LocalDate.now()))throw new IllegalArgumentException("Driver licence is expired or missing");}
 private void validateVehicleForRoute(Vehicle v,RentalRoute r){if(v.getStatus()==Vehicle.Status.MAINTENANCE||v.getStatus()==Vehicle.Status.INACTIVE)throw new IllegalArgumentException("Vehicle is not operational");if(v.getInsuranceExpiry()==null||v.getInsuranceExpiry().isBefore(LocalDate.now()))throw new IllegalArgumentException("Vehicle insurance is expired or missing");if(r.isInterstate()){if(v.getPermitExpiry()==null||v.getPermitExpiry().isBefore(LocalDate.now()))throw new IllegalArgumentException("Interstate permit is expired or missing");if(v.getCoveredStates()==null||!v.getCoveredStates().contains(r.getToStateCode()))throw new IllegalArgumentException("Vehicle permit does not cover destination state");}}
 private RentalBooking owned(String id,String vendorId){RentalBooking b=bookings.findById(id).orElseThrow();if(!Objects.equals(b.getVendorId(),vendorId))throw new IllegalArgumentException("Booking not owned by vendor");return b;}
 private RentalBooking driverOwned(String id,String driverId){RentalBooking b=bookings.findById(id).orElseThrow();if(!Objects.equals(b.getDriverId(),driverId))throw new IllegalArgumentException("Booking is not assigned to this driver");return b;}
 private boolean allowedVendor(RentalBooking.Status c,RentalBooking.Status n){return switch(c){case REQUESTED->Set.of(RentalBooking.Status.VENDOR_CONFIRMED,RentalBooking.Status.REJECTED,RentalBooking.Status.CANCELLED).contains(n);case DRIVER_ASSIGNED->Set.of(RentalBooking.Status.VENDOR_CONFIRMED,RentalBooking.Status.CANCELLED).contains(n);case VENDOR_CONFIRMED->Set.of(RentalBooking.Status.CUSTOMER_CONFIRMED,RentalBooking.Status.DRIVER_ASSIGNED,RentalBooking.Status.CANCELLED).contains(n);default->false;};}
 private RentalBooking.Status parseStatus(String s){try{return RentalBooking.Status.valueOf(s.toUpperCase());}catch(Exception e){throw new IllegalArgumentException("Invalid rental status");}}
 private void change(RentalBooking b,RentalBooking.Status n,User actor,String note){String old=b.getStatus()==null?"":b.getStatus().name();b.setStatus(n);b.setUpdatedAt(Instant.now());b.getStatusHistory().add(history(n.name(),actor,note==null?"":note,Instant.now()));audit("BOOKING",b.getId(),"STATUS",actor,old,n.name(),note);}
 private StatusHistory history(String s,User u,String note,Instant at){return StatusHistory.builder().status(s).actorId(u.getId()).actorEmail(u.getEmail()).note(note).changedAt(at).build();}
 private void audit(String type,String id,String action,User u,String old,String next,String reason){audits.save(RentalAudit.builder().entityType(type).entityId(id).action(action).actorId(u.getId()).actorEmail(u.getEmail()).role(u.getRoles().toString()).oldValue(old).newValue(next).reason(reason).createdAt(Instant.now()).build());}
 private void notifyUsers(String uid,String title,String msg,String type){notifications.create(uid,title,msg,type);}
 private void notifyDriver(RentalBooking b,String title){if(b.getDriverId()!=null)drivers.findById(b.getDriverId()).ifPresent(d->notifyUsers(d.getUserId(),title,"Booking "+b.getBookingNumber()+" is ready for your action.","RENTAL_DRIVER"));}
 private void releaseVehicle(RentalBooking b){if(b.getVehicleId()!=null)vehicles.findById(b.getVehicleId()).ifPresent(v->{if(v.getStatus()==Vehicle.Status.BOOKED){v.setStatus(Vehicle.Status.AVAILABLE);vehicles.save(v);}});}
 private void ensureEndKm(Double start,double end){if(start==null)throw new IllegalArgumentException("Starting KM is missing");if(end<start)throw new IllegalArgumentException("Ending KM cannot be less than starting KM");}
 private void validateTripTime(RentalBooking b,Double start,Double end){if(end==null||start==null||b.getStartAt()==null)return;long mins=Math.max(1,Duration.between(b.getStartAt(),Instant.now()).toMinutes());double km=end-start;if(km/mins*60>maxKmPerHour)throw new IllegalArgumentException("KM reading is inconsistent with trip duration; admin review required");}
 private void validateAddress(String a,String m){if(a==null||a.trim().length()<10)throw new IllegalArgumentException(m+" (minimum 10 characters)");}
 private String required(String x,String m){if(x==null||x.isBlank())throw new IllegalArgumentException(m);return x.trim();}
 private double nvl(Double x){return x==null?0:x;}
 private void admin(String email){if(!user(email).getRoles().contains(User.Role.ADMIN))throw new IllegalArgumentException("Admin access required");}
}
