package com.asmj.marketplace.job.service;
import com.asmj.marketplace.job.model.*; import com.asmj.marketplace.job.repository.*; import com.asmj.marketplace.application.model.JobApplication; import com.asmj.marketplace.application.repository.JobApplicationRepository; import com.asmj.marketplace.post.model.Post; import com.asmj.marketplace.post.repository.PostRepository; import com.asmj.marketplace.user.model.User; import com.asmj.marketplace.user.repository.UserRepository; import com.asmj.marketplace.vendor.repository.VendorRepository; import com.asmj.marketplace.notification.service.NotificationService; import com.asmj.marketplace.common.model.StatusHistory; import lombok.RequiredArgsConstructor; import org.springframework.stereotype.Service; import java.time.*; import java.util.*;
@Service @RequiredArgsConstructor public class JobMarketplaceService {
 private final UserRepository users; private final VendorRepository vendors; private final PostRepository posts; private final JobListingRepository jobs; private final EmployerProfileRepository employers; private final JobApplicationRepository apps; private final JobInterviewRepository interviews; private final JobOfferRepository offers; private final NotificationService notifications;
 private User user(String email){return users.findByEmailIgnoreCase(email).orElseThrow(()->new IllegalArgumentException("User not found"));}
 private String vendorId(User u){return vendors.findByUserId(u.getId()).orElseThrow(()->new IllegalArgumentException("Vendor profile not found")).getId();}
 public EmployerProfile saveEmployer(String email, EmployerProfile p){User u=user(email);String v=vendorId(u);var old=employers.findByVendorId(v).orElse(EmployerProfile.builder().vendorId(v).createdAt(Instant.now()).build());old.setCompanyName(p.getCompanyName());old.setLegalName(p.getLegalName());old.setWebsite(p.getWebsite());old.setDescription(p.getDescription());old.setIndustry(p.getIndustry());old.setCompanySize(p.getCompanySize());old.setLogoUrl(p.getLogoUrl());old.setAddress(p.getAddress());old.setCity(p.getCity());old.setState(p.getState());old.setPincode(p.getPincode());old.setContactName(p.getContactName());old.setContactEmail(p.getContactEmail());old.setContactMobile(p.getContactMobile());old.setUpdatedAt(Instant.now());return employers.save(old);}
 public EmployerProfile myEmployer(String email){return employers.findByVendorId(vendorId(user(email))).orElse(null);}
 public JobListing create(String email, CreateJob r){User u=user(email);String v=vendorId(u); if(r.title()==null||r.title().isBlank())throw new IllegalArgumentException("Job title is required"); if(r.applicationDeadline()!=null&&r.applicationDeadline().isBefore(Instant.now()))throw new IllegalArgumentException("Application deadline must be in the future"); Instant now=Instant.now();Post p=posts.save(Post.builder().vendorId(v).categoryId(r.categoryId()).type("JOB").title(r.title().trim()).slug(r.title().toLowerCase().replaceAll("[^a-z0-9]+","-")).description(r.description()).price(r.maxSalary()).priceType(r.salaryPeriod()).images(r.images()==null?new ArrayList<>():r.images()).attachments(r.attachments()==null?new ArrayList<>():r.attachments()).location(r.location()).attributes(r.attributes()==null?new HashMap<>():r.attributes()).status(Post.PostStatus.PENDING_APPROVAL).approvalStatus(Post.PostStatus.PENDING_APPROVAL).createdAt(now).updatedAt(now).build()); JobListing j=JobListing.builder().postId(p.getId()).vendorId(v).employmentType(r.employmentType()).workMode(r.workMode()).experienceLevel(r.experienceLevel()).department(r.department()).education(r.education()).locationText(r.locationText()).minSalary(r.minSalary()).maxSalary(r.maxSalary()).salaryPeriod(r.salaryPeriod()).currency(r.currency()==null?"INR":r.currency()).salaryVisible(r.salaryVisible()).openings(r.openings()==null?1:r.openings()).applicationDeadline(r.applicationDeadline()).skills(r.skills()==null?new ArrayList<>():r.skills()).benefits(r.benefits()==null?new ArrayList<>():r.benefits()).screeningQuestions(r.screeningQuestions()==null?new ArrayList<>():r.screeningQuestions()).resumeRequired(r.resumeRequired()).applicationInstructions(r.applicationInstructions()).createdAt(now).updatedAt(now).build();return jobs.save(j);}
 public List<JobListing> myJobs(String email){return jobs.findByVendorIdOrderByCreatedAtDesc(vendorId(user(email)));}
 public List<JobListing> publicJobs(){return jobs.findAll().stream().filter(j->posts.findById(j.getPostId()).map(p->p.getStatus()==Post.PostStatus.PUBLISHED).orElse(false)).toList();}
 public JobListing one(String id){return jobs.findById(id).orElseThrow(()->new IllegalArgumentException("Job not found"));}
 public JobApplication apply(String email,String appId,String resumeUrl,String coverLetter,Map<String,String> answers){User u=user(email);JobApplication a=apps.findById(appId).orElseThrow(()->new IllegalArgumentException("Application not found")); if(!Objects.equals(a.getUserId(),u.getId()))throw new IllegalArgumentException("You cannot update this application"); if(a.getStatus()!=null&&!Set.of("SUBMITTED","UNDER_REVIEW").contains(a.getStatus()))throw new IllegalArgumentException("Application is no longer editable"); a.setCoverLetter(coverLetter);a.setResumeUrl(resumeUrl);if(a.getStatusHistory()==null)a.setStatusHistory(new ArrayList<>());if(answers!=null)a.setInterviewNotes("SCREENING_ANSWERS:"+answers);a.setUpdatedAt(Instant.now());return apps.save(a);}
 public JobInterview scheduleInterview(String email,String applicationId,InterviewRequest r){User u=user(email);String v=vendorId(u);JobApplication a=apps.findById(applicationId).orElseThrow(()->new IllegalArgumentException("Application not found"));if(!Objects.equals(a.getVendorId(),v))throw new IllegalArgumentException("Not your application");if(r.scheduledAt()==null||r.scheduledAt().isBefore(Instant.now()))throw new IllegalArgumentException("Interview time must be in the future");JobInterview i=interviews.findByApplicationId(applicationId).orElse(JobInterview.builder().applicationId(applicationId).createdAt(Instant.now()).build());i.setPostId(a.getPostId());i.setVendorId(v);i.setCandidateId(a.getUserId());i.setScheduledAt(r.scheduledAt());i.setDurationMinutes(r.durationMinutes()==null?30:r.durationMinutes());i.setMode(r.mode());i.setMeetingUrl(r.meetingUrl());i.setLocation(r.location());i.setInterviewerName(r.interviewerName());i.setInterviewerEmail(r.interviewerEmail());i.setNotes(r.notes());i.setStatus("SCHEDULED");i.setUpdatedAt(Instant.now());JobInterview saved=interviews.save(i);a.setStatus("INTERVIEW");a.setInterviewDate(r.scheduledAt());a.setInterviewNotes(r.notes());a.setUpdatedAt(Instant.now());apps.save(a);notifications.create(a.getUserId(),"Interview scheduled","Your job interview has been scheduled for "+r.scheduledAt(),"JOB_INTERVIEW");return saved;}
 public List<JobInterview> myInterviews(String email){return interviews.findByCandidateIdOrderByScheduledAtDesc(user(email).getId());} public List<JobInterview> vendorInterviews(String email){return interviews.findByVendorIdOrderByScheduledAtDesc(vendorId(user(email)));}
 public JobOffer createOffer(String email,String applicationId,OfferRequest r){User u=user(email);String v=vendorId(u);JobApplication a=apps.findById(applicationId).orElseThrow(()->new IllegalArgumentException("Application not found"));if(!Objects.equals(a.getVendorId(),v))throw new IllegalArgumentException("Not your application");if(r.annualCtc()==null||r.annualCtc()<=0)throw new IllegalArgumentException("Annual CTC is required");JobOffer o=offers.findByApplicationId(applicationId).orElse(JobOffer.builder().applicationId(applicationId).createdAt(Instant.now()).build());o.setPostId(a.getPostId());o.setVendorId(v);o.setCandidateId(a.getUserId());o.setAnnualCtc(r.annualCtc());o.setCurrency(r.currency()==null?"INR":r.currency());o.setDesignation(r.designation());o.setJoiningLocation(r.joiningLocation());o.setJoiningDate(r.joiningDate());o.setExpiresAt(r.expiresAt());o.setNotes(r.notes());o.setStatus("SENT");o.setUpdatedAt(Instant.now());a.setStatus("OFFERED");a.setUpdatedAt(Instant.now());apps.save(a);JobOffer saved=offers.save(o);notifications.create(a.getUserId(),"Job offer received","You have received a job offer. Review the offer details.","JOB_OFFER");return saved;}
 public List<JobOffer> myOffers(String email){return offers.findByCandidateIdOrderByCreatedAtDesc(user(email).getId());} public List<JobOffer> vendorOffers(String email){return offers.findByVendorIdOrderByCreatedAtDesc(vendorId(user(email)));}
 public JobOffer respondOffer(String email,String id,String status){User u=user(email);JobOffer o=offers.findById(id).orElseThrow(()->new IllegalArgumentException("Offer not found"));if(!Objects.equals(o.getCandidateId(),u.getId()))throw new IllegalArgumentException("You cannot update this offer");String n=status==null?"":status.toUpperCase();if(!Set.of("ACCEPTED","DECLINED").contains(n))throw new IllegalArgumentException("Offer status must be ACCEPTED or DECLINED");if(o.getExpiresAt()!=null&&o.getExpiresAt().isBefore(Instant.now()))throw new IllegalArgumentException("Offer has expired");o.setStatus(n);o.setUpdatedAt(Instant.now());JobOffer saved=offers.save(o);vendors.findById(o.getVendorId()).ifPresent(v->notifications.create(v.getUserId(),"Job offer response","Candidate has "+n.toLowerCase()+" your job offer.","JOB_OFFER_RESPONSE"));return saved;}
 public record CreateJob(String categoryId,String title,String description,String employmentType,String workMode,String experienceLevel,String department,String education,String locationText,Double minSalary,Double maxSalary,String salaryPeriod,String currency,boolean salaryVisible,Integer openings,Instant applicationDeadline,List<String> skills,List<String> benefits,List<JobListing.ScreeningQuestion> screeningQuestions,boolean resumeRequired,String applicationInstructions,List<String> images,List<Post.MediaItem> attachments,Post.Location location,Map<String,Object> attributes){}
 public record InterviewRequest(Instant scheduledAt,Integer durationMinutes,String mode,String meetingUrl,String location,String interviewerName,String interviewerEmail,String notes){}
 public record OfferRequest(Double annualCtc,String currency,String designation,String joiningLocation,Instant joiningDate,Instant expiresAt,String notes){}
}
