import {useEffect,useMemo,useState} from "react";
import {Search,ShieldOff,RotateCcw,Eye,Filter} from "lucide-react";
import {getAdminListings,suspendListing,reactivateListing} from "../../api/adminApi";
const idOf=x=>x?.id||x?._id;
export default function AdminListings(){
 const [items,setItems]=useState([]),[q,setQ]=useState(""),[status,setStatus]=useState("ALL"),[busy,setBusy]=useState(""),[notice,setNotice]=useState("");
 const load=()=>getAdminListings().then(r=>setItems(r.data?.data||r.data||[])).catch(e=>setNotice(e.response?.data?.message||"Unable to load listings."));
 useEffect(()=>{load()},[]);
 const filtered=useMemo(()=>items.filter(x=>(status==="ALL"||String(x.status||"")===status)&&(!q||[x.title,x.type,x.vendorId,x.categoryId].some(v=>String(v||"").toLowerCase().includes(q.toLowerCase())))),[items,q,status]);
 const act=async(id,fn)=>{setBusy(id);setNotice("");try{await fn(id);await load()}catch(e){setNotice(e.response?.data?.message||"Action failed.")}finally{setBusy("")}};
 return <div className="page-shell admin-bg"><div className="mb-6"><p className="eyebrow">ADMIN CONTROL</p><h1 className="page-title">Listing management</h1><p className="mt-2 text-sm text-slate-500">Search every listing, inspect its current state, and suspend or reactivate marketplace content.</p></div>{notice&&<div className="mb-5 rounded-2xl border border-amber-200 bg-amber-50 px-4 py-3 text-sm font-semibold text-amber-800">{notice}</div>}<div className="card mb-5 flex flex-col gap-3 p-4 md:flex-row"><div className="relative flex-1"><Search className="absolute left-3 top-3.5 text-slate-400" size={17}/><input className="input pl-10" placeholder="Search title, type, vendor or category" value={q} onChange={e=>setQ(e.target.value)}/></div><div className="relative"><Filter className="pointer-events-none absolute left-3 top-3.5 text-slate-400" size={16}/><select className="input pl-9" value={status} onChange={e=>setStatus(e.target.value)}><option value="ALL">All statuses</option>{["DRAFT","SUBMITTED","PENDING_APPROVAL","APPROVED","REJECTED","PUBLISHED","SUSPENDED","EXPIRED","ARCHIVED"].map(x=><option key={x}>{x}</option>)}</select></div></div><div className="space-y-3">{filtered.map(x=>{const id=idOf(x),s=x.status||"—";return <div className="card p-4" key={id}><div className="flex flex-col gap-4 lg:flex-row lg:items-center"><div className="flex min-w-0 flex-1 items-center gap-4"><div className="grid h-16 w-16 shrink-0 place-items-center overflow-hidden rounded-2xl bg-slate-100">{x.images?.[0]?<img src={x.images[0]} alt="" className="h-full w-full object-cover"/>:<Eye size={20} className="text-slate-400"/>}</div><div className="min-w-0"><h3 className="truncate font-black">{x.title||"Untitled listing"}</h3><p className="mt-1 text-sm text-slate-500">{x.type||"Listing"} · Category: {x.categoryId||"—"}</p><p className="mt-1 text-xs text-slate-400">ID: {id} · Vendor: {x.vendorId||"—"}</p></div></div><div className="flex flex-wrap items-center gap-2"><span className="badge">{s}</span>{s==="SUSPENDED"?<button className="btn-primary" disabled={busy===id} onClick={()=>act(id,reactivateListing)}><RotateCcw size={15}/> Reactivate</button>:<button className="btn-secondary" disabled={busy===id} onClick={()=>act(id,suspendListing)}><ShieldOff size={15}/> Suspend</button>}</div></div></div>})}{!filtered.length&&<div className="card p-10 text-center text-sm text-slate-400">No listings match the selected filters.</div>}</div></div>
}
