import {useEffect,useState} from "react";
import {CheckCircle2,Printer,XCircle} from "lucide-react";
import {getPendingPrintoutServices,approvePrintoutService,rejectPrintoutService} from "../../api/adminApi";

export default function PrintoutApprovals(){
 const [items,setItems]=useState([]),[loading,setLoading]=useState(true),[notice,setNotice]=useState("");
 const load=()=>{setLoading(true);getPendingPrintoutServices().then(r=>setItems(r.data?.data||[])).catch(e=>setNotice(e.response?.data?.message||"Could not load printout approvals")).finally(()=>setLoading(false));};
 useEffect(load,[]);
 const act=async(id,fn)=>{try{await fn(id);setNotice("Printout service status updated");load();}catch(e){setNotice(e.response?.data?.message||"Action failed");}};
 return <div className="page-shell admin-bg"><div className="mb-6"><p className="eyebrow">ADMIN CONTROL</p><h1 className="page-title">Printout service approvals</h1><p className="mt-2 text-sm text-slate-500">Review vendor printing services before they become visible to marketplace users.</p></div>{notice&&<div className="alert mb-5">{notice}</div>}{loading?<div className="card p-8 text-center text-slate-500">Loading approvals…</div>:<div className="grid gap-5 lg:grid-cols-2">{items.map(item=><div className="card p-6" key={item.id}><div className="flex items-start justify-between gap-3"><div className="flex items-center gap-3"><div className="grid h-12 w-12 place-items-center rounded-2xl bg-indigo-100 text-indigo-700"><Printer size={22}/></div><div><h2 className="font-black">{item.serviceName}</h2><p className="text-xs text-slate-500">Vendor ID: {item.vendorId}</p></div></div><span className="status-pill bg-amber-100 text-amber-700">{item.approvalStatus||"PENDING"}</span></div><p className="mt-4 text-sm text-slate-600">{item.description||"No description provided."}</p><div className="mt-4 grid grid-cols-2 gap-2 rounded-2xl bg-slate-50 p-4 text-sm"><span>B&W single: ₹{item.bwSingleRate}</span><span>B&W double: ₹{item.bwDoubleRate}</span><span>Colour single: ₹{item.colorSingleRate}</span><span>Colour double: ₹{item.colorDoubleRate}</span><span>Pickup: {item.pickupAvailable?"Yes":"No"}</span><span>Home delivery: {item.homeDeliveryAvailable?"Yes":"No"}</span></div><div className="mt-5 flex flex-wrap gap-2"><button className="btn-primary" onClick={()=>act(item.id,approvePrintoutService)}><CheckCircle2 size={16}/> Approve</button><button className="btn-secondary text-red-600" onClick={()=>act(item.id,rejectPrintoutService)}><XCircle size={16}/> Reject</button></div></div>)}{!items.length&&<div className="card p-10 text-center text-slate-500 lg:col-span-2">No pending printout services.</div>}</div>}</div>;
}
